In [ ]:

import json
import time
import os
import pandas as pd

In [ ]:
vmcount=1
size=1
tcount=1
task=1
vm=1
data = {}

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
f = open('/content/drive/MyDrive/colab/Cloudsim/exe/data_10000_5'+'.json')
data = json.load(f)
vmcount1= data['vmcount'][0]
vmcount=vmcount1
size=data['tcount'][0]

In [ ]:
def Fun1(solution,size1):
  list1 = [0] * data['vmcount'][0]
  tid=[]
  vid=[]
  start_t=[]
  finish_t=[]
  exe_t=[]
  val = 0.0
  #print(solution)
  #print(int(round(solution[0])))
  for i in range(len(solution)):
    solution[i]=round(solution[i])
    if(round(solution[i])!=0.0):
      start=list1[int(abs(round(solution[i],0)))-1]
      list1[int(abs(round(solution[i],0)))-1]=list1[int(abs(round(solution[i],0)))-1] + data['task'][0]/data['VM'][int(abs(round(solution[i],0)))-1]
      finish=list1[int(abs(round(solution[i],0)))-1]
      tid.append(i)
      vid.append(abs(round(solution[i],0)))
      start_t.append(start)
      finish_t.append(finish)
      exe_t.append(finish-start)

    else:
      list1[int(abs(round(solution[i])))]=list1[int(abs(round(solution[i],0)))] + data['task'][0]/data['VM'][int(abs(round(solution[i])))]
      tid.append(i)
      vid.append(abs(round(solution[i],0)))
      start_t.append(start)
      finish_t.append(finish)
      exe_t.append(finish-start)
  print(max(list1))
  l=max(list1)
  uitli=[x/l for x in list1]
  import numpy as np
  utlim=np.mean(uitli)*100
  print(len(tid))
  simula={'task_id': tid, 'VM_ID': vid, 'Start_time': start_t,'Finish_time':finish_t,'Exec_time':exe_t}
  df=pd.DataFrame(simula)
  print(df)

  return l, utlim,df

In [ ]:
vm=5
count=10000
number=100

In [ ]:
algo="QSA1"
size=500
f1 = open("/content/drive/MyDrive/colab/Cloudsim/exe/all/"+algo+'/sample_'+str(size)+'_5'+'.json')
data1 = json.load(f1)
solution=data1['name']
solution
exe, utili,df=Fun1(solution,size)
average_start=df['Start_time'].mean()
average_finish=df['Finish_time'].mean()
average_exe=df['Exec_time'].mean()
power=exe*utili*0.0003

print("Energy in KWH",power)

931.4285714285683
500
     task_id  VM_ID  Start_time  Finish_time  Exec_time
0          0      1    0.000000    16.000000  16.000000
1          1      2    0.000000     8.000000   8.000000
2          2      1   16.000000    32.000000  16.000000
3          3      1   32.000000    48.000000  16.000000
4          4      3    0.000000     5.714286   5.714286
..       ...    ...         ...          ...        ...
495      495      3  920.000000   925.714286   5.714286
496      496      3  925.714286   931.428571   5.714286
497      497      4  920.000000   925.714286   5.714286
498      498      1  912.000000   928.000000  16.000000
499      499      4  925.714286   931.428571   5.714286

[500 rows x 5 columns]
Energy in KWH 22.313142857142815

In [ ]:
algo1=[]
tasks=[]
exe1=[]
utili1=[]
average_start=[]
average_finish=[]
average_exe=[]
power=[]
df_start={'tasks':["100","500","1000","1500","2000","2500"]}
df_finish={'tasks':["100","500","1000","1500","2000","2500"]}
df_aexe={'tasks':["100","500","1000","1500","2000","2500"]}
df_util={'tasks':["100","500","1000","1500","2000","2500"]}
df_exe={'tasks':["100","500","1000","1500","2000","2500"]}
df_power={'tasks':["100","500","1000","1500","2000","2500"]}
df2_start=pd.DataFrame(df_start)
df2_exe=pd.DataFrame(df_exe)
df2_finish=pd.DataFrame(df_finish)
df2_aexe=pd.DataFrame(df_aexe)
df2_util=pd.DataFrame(df_util)
df2_power=pd.DataFrame(df_power)
res = os.listdir("/content/drive/MyDrive/colab/Cloudsim/exe/all/")
algo = ["SSpiderO",    "SSpiderA",    "SSO",    "SSA1",    "SSA",    "SRSR",    "SLO",    "SLO2",    "SLO1",    "SHO",    "SFO1",
    "SFO",    "ServalOA",    "SeaHO",    "POA",    "PFA",    "OOA",    "NGO",    "NMRA1",    "NMRA",    "MSA",    "MRFO1",    "MRFO",    "MPA",    "MGO",    "MFO",    "JA2",    "JA1",    "JA",   "HHO",
    "HGS",    "HBA",    "GWO3",    "GWO2",    "GWO1",    "GTO2",    "GTO1",    "GTO",    "GOA",    "GJO",    "FOX",    "FOA1",    "FOA",    "FOA2",    "FFO",    "FFA",    "FA",
    "ESOA",    "EHO",    "DO",    "DMOA1",    "DMOA",    "CSO",    "CSA",    "CoatiOA",    "COA",
    "BSA",  "BBO", "PSO", "PSO2", "PSO3", "PSO4", "PSO5", "PSO6", "PSO7",
    "GA", "GA1", "GA2", "GA3", "GA4",
    "ABC", "ACOR", "AGTO", "AGTO1",
    "ALO", "ALO1", "AO", "ARO", "ARO1", "ARO2",
    "AVOA", "BA", "BA1", "BA2",
    "BBOA", "BWO", "EOA", "IWO",
    "SBO", "SBO1", "SMA", "SMA1", "SOA", "SOS",
    "TPO", "TSA", "VCS", "VCS1",
    "WHO", "AOA", "CEM", "CGO",
    "CircleSA", "GBO", "HC", "HC1", "INFO", "PSS",
    "RUN", "SCA", "SCA1", "SCA2", "SCA3",
    "SHIO", "TS", "HS", "HS1",
    "AEO", "AEO1", "AEO2", "AEO3", "AEO4",
    "GCO", "GCO1", "WCA", "CRO", "CRO1",
    "DE", "DE1", "DE2", "DE3",
    "EP", "EP1", "ES", "ES1", "ES2", "ES3",
    "FPA", "MA", "SHADE", "SHADE2",
    "BRO", "BRO1", "BSO", "BSO1",
    "CA", "CHIO", "CHIO1", "FBIO", "FBIO1",
    "GSKA", "GSKA1", "HBO", "HCO",
    "ICA", "LCO", "LCO1", "LCO2",
    "WarSO", "TOA", "TLO", "TLO1", "TLO2",
    "SSDO", "SPBO", "SPBO1", "SARO", "SARO1",
    "QSA", "QSA1", "QSA2", "QSA3", "QSA4",
    "ArchOA", "ASO", "CDO", "EFO", "EFO1",
    "EO", "EO1", "EO2", "EVO",
    "FLA", "HGSO", "MVO", "MVO1",
    "NRO", "RIME", "SA", "SA1", "SA2",
    "WDO", "TWO", "TWO1", "TWO2", "TWO3",
    "BeesA", "BeesA1", "BeesA2",
    "BES", "BFO", "BFO1", "ZOA",
    "WOA", "WOA1", "WaOA", "TSO", "TDO", "STO" ]
tsize=["100","500","1000","1500","2000","2500"]

algo =res
#algo = ["SSpiderO",    "SSpiderA","SSO",    "SSA1"]
tif_file="data_10000_5.json"
for i in range(len(algo)):
  algo1=[]
  tasks=[]
  exe1=[]
  utili1=[]
  average_start=[]
  average_finish=[]
  average_exe=[]
  power=[]
  for j in tsize:
    try:
      print(j)
      f1 = open("/content/drive/MyDrive/colab/Cloudsim/exe/all/"+algo[i]+'/sample_'+j+'_5'+'.json')
      data1 = json.load(f1)
      solution=data1['name']
      solution
      exe, utili,df=Fun1(solution,size)
      f=algo[i]
      algo1.append(f)
      tasks.append(j)
      exe1.append(exe)
      average_exe.append(df['Exec_time'].mean())
      average_start.append(df['Start_time'].mean())
      average_finish.append(df['Finish_time'].mean())
      utili1.append(utili)
      power.append(exe*utili*0.0003)
      !mkdir -p "/content/"{f}
      simula={'algo': algo1, 'tasks': tasks, 'Average_Start_time': average_start,'Average_Finish_time':average_finish,'average_Exec_time':average_exe,'average_utlization':utili1,'Execution':exe1,'Power':power}
      df=pd.DataFrame(simula)
      df.to_csv(f+'/sample_'+str(j)+'_5.csv')
      %cp -r /content/{f} "/content/drive/MyDrive/colab/Cloudsim/exe/all"
    except Exception as error:
      print("An exception occurred",error)
  try:
    df2_exe.insert(1, f,exe1)
    df2_start.insert(1, f,average_start)
    df2_finish.insert(1, f,average_finish)
    df2_aexe.insert(1, f,average_exe)
    df2_util.insert(1, f,utili1)
    df2_power.insert(1, f,power)
  except:
    print("algo not found")
simula1={'algo': algo1, 'tasks': tasks, 'Average_Start_time': average_start,'Average_Finish_time':average_finish,'average_Exec_time':average_exe,'average_utlization':utili1,'Execution':exe1,'Power':power}
df1=pd.DataFrame(simula1)
print(df1)
df.to_csv('analysis_5.csv')
df2_exe.to_csv('exe_5.csv')
df2_finish.to_csv('start_5.csv')
df2_start.to_csv('finish_5.csv')
df2_aexe.to_csv('aexe_5.csv')
df2_util.to_csv('util_5.csv')
df2_power.to_csv('power_5.csv')
%cp -r /content/{f} "/content/drive/MyDrive/Cloudsim/exe"

Streaming output truncated to the last 5000 lines.
1498     1498      1  5120.000000  5136.000000  16.000000
1499     1499      2  3920.000000  3928.000000   8.000000

[1500 rows x 5 columns]
2000
7728.0
2000
      task_id  VM_ID   Start_time  Finish_time  Exec_time
0           0      3     0.000000     5.714286   5.714286
1           1      0     0.000000     5.714286   5.714286
2           2      2     0.000000     8.000000   8.000000
3           3      3     5.714286    11.428571   5.714286
4           4      2     8.000000    16.000000   8.000000
...       ...    ...          ...          ...        ...
1995     1995      2  4960.000000  4968.000000   8.000000
1996     1996      3  3371.428571  3377.142857   5.714286
1997     1997      2  4968.000000  4976.000000   8.000000
1998     1998      1  7712.000000  7728.000000  16.000000
1999     1999      2  4976.000000  4984.000000   8.000000

[2000 rows x 5 columns]
2500
11328.0
2500
      task_id  VM_ID    Start_time   Finish_time  Exec_time
0           0      2      0.000000      8.000000   8.000000
1           1      3      0.000000      5.714286   5.714286
2           2      2      8.000000     16.000000   8.000000
3           3      3      5.714286     11.428571   5.714286
4           4      2     16.000000     24.000000   8.000000
...       ...    ...           ...           ...        ...
2495     2495      2   5904.000000   5912.000000   8.000000
2496     2496      3   4080.000000   4085.714286   5.714286
2497     2497      1  11312.000000  11328.000000  16.000000
2498     2498      3   4085.714286   4091.428571   5.714286
2499     2499      4   1920.000000   1925.714286   5.714286

[2500 rows x 5 columns]
100
304.0
100
    task_id  VM_ID  Start_time  Finish_time  Exec_time
0         0      2    0.000000     8.000000   8.000000
1         1      2    8.000000    16.000000   8.000000
2         2      0    8.000000    16.000000   8.000000
3         3      1   16.000000    32.000000  16.000000
4         4      2   16.000000    24.000000   8.000000
..      ...    ...         ...          ...        ...
95       95      4  194.285714   200.000000   5.714286
96       96      2  280.000000   288.000000   8.000000
97       97      2  288.000000   296.000000   8.000000
98       98      0  288.000000   296.000000   8.000000
99       99      4  200.000000   205.714286   5.714286

[100 rows x 5 columns]
500
An exception occurred local variable 'start' referenced before assignment
1000
3904.0
1000
     task_id  VM_ID   Start_time  Finish_time  Exec_time
0          0      4     0.000000     5.714286   5.714286
1          1      2     0.000000     8.000000   8.000000
2          2      2     8.000000    16.000000   8.000000
3          3      2    16.000000    24.000000   8.000000
4          4      2    24.000000    32.000000   8.000000
..       ...    ...          ...          ...        ...
995      995      4  1731.428571  1737.142857   5.714286
996      996      0  1731.428571  1737.142857   5.714286
997      997      2  3560.000000  3568.000000   8.000000
998      998      2  3568.000000  3576.000000   8.000000
999      999      0  3568.000000  3576.000000   8.000000

[1000 rows x 5 columns]
1500
5872.0
1500
      task_id  VM_ID   Start_time  Finish_time  Exec_time
0           0      4     0.000000     5.714286   5.714286
1           1      2     0.000000     8.000000   8.000000
2           2      4     5.714286    11.428571   5.714286
3           3      0     5.714286    11.428571   5.714286
4           4      2     8.000000    16.000000   8.000000
...       ...    ...          ...          ...        ...
1495     1495      4  1902.857143  1908.571429   5.714286
1496     1496      2  5832.000000  5840.000000   8.000000
1497     1497      2  5840.000000  5848.000000   8.000000
1498     1498      4  1908.571429  1914.285714   5.714286
1499     1499      3   377.142857   382.857143   5.714286

[1500 rows x 5 columns]
2000
An exception occurred local variable 'start' referenced before assignment
2500
9792.0
2500
      task_id  VM_ID   Start_time  Finish_time  Exec_time
0           0      4     0.000000     5.714286   5.714286
1           1      2     0.000000     8.000000   8.000000
2           2      2     8.000000    16.000000   8.000000
3           3      0     8.000000    16.000000   8.000000
4           4      2    16.000000    24.000000   8.000000
...       ...    ...          ...          ...        ...
2495     2495      2  9768.000000  9776.000000   8.000000
2496     2496      0  9768.000000  9776.000000   8.000000
2497     2497      4  3102.857143  3108.571429   5.714286
2498     2498      2  9776.000000  9784.000000   8.000000
2499     2499      2  9784.000000  9792.000000   8.000000

[2500 rows x 5 columns]
algo not found
100
188.57142857142858
100
    task_id  VM_ID  Start_time  Finish_time  Exec_time
0         0      4    0.000000     5.714286   5.714286
1         1      2    0.000000     8.000000   8.000000
2         2      3    0.000000     5.714286   5.714286
3         3      4    5.714286    11.428571   5.714286
4         4      4   11.428571    17.142857   5.714286
..      ...    ...         ...          ...        ...
95       95      1  160.000000   176.000000  16.000000
96       96      4  177.142857   182.857143   5.714286
97       97      3  177.142857   182.857143   5.714286
98       98      4  182.857143   188.571429   5.714286
99       99      3  182.857143   188.571429   5.714286

[100 rows x 5 columns]
500
An exception occurred local variable 'start' referenced before assignment
1000
1885.7142857142915
1000
     task_id  VM_ID   Start_time  Finish_time  Exec_time
0          0      3     0.000000     5.714286   5.714286
1          1      2     0.000000     8.000000   8.000000
2          2      1     0.000000    16.000000  16.000000
3          3      3     5.714286    11.428571   5.714286
4          4      3    11.428571    17.142857   5.714286
..       ...    ...          ...          ...        ...
995      995      4  1874.285714  1880.000000   5.714286
996      996      3  1880.000000  1885.714286   5.714286
997      997      1  1776.000000  1792.000000  16.000000
998      998      1  1792.000000  1808.000000  16.000000
999      999      1  1808.000000  1824.000000  16.000000

[1000 rows x 5 columns]
1500
2811.4285714285875
1500
      task_id  VM_ID   Start_time  Finish_time  Exec_time
0           0      4     0.000000     5.714286   5.714286
1           1      3     0.000000     5.714286   5.714286
2           2      4     5.714286    11.428571   5.714286
3           3      1     0.000000    16.000000  16.000000
4           4      3     5.714286    11.428571   5.714286
...       ...    ...          ...          ...        ...
1495     1495      3  2800.000000  2805.714286   5.714286
1496     1496      2  2776.000000  2784.000000   8.000000
1497     1497      2  2784.000000  2792.000000   8.000000
1498     1498      2  2792.000000  2800.000000   8.000000
1499     1499      3  2805.714286  2811.428571   5.714286

[1500 rows x 5 columns]
2000
3800.0000000000273
2000
      task_id  VM_ID   Start_time  Finish_time  Exec_time
0           0      2     0.000000     8.000000   8.000000
1           1      1     0.000000    16.000000  16.000000
2           2      1    16.000000    32.000000  16.000000
3           3      4     0.000000     5.714286   5.714286
4           4      3     0.000000     5.714286   5.714286
...       ...    ...          ...          ...        ...
1995     1995      2  3720.000000  3728.000000   8.000000
1996     1996      3  3611.428571  3617.142857   5.714286
1997     1997      4  3782.857143  3788.571429   5.714286
1998     1998      4  3788.571429  3794.285714   5.714286
1999     1999      4  3794.285714  3800.000000   5.714286

[2000 rows x 5 columns]
2500
4668.57142857142
2500
      task_id  VM_ID   Start_time  Finish_time  Exec_time
0           0      3     0.000000     5.714286   5.714286
1           1      2     0.000000     8.000000   8.000000
2           2      3     5.714286    11.428571   5.714286
3           3      2     8.000000    16.000000   8.000000
4           4      2    16.000000    24.000000   8.000000
...       ...    ...          ...          ...        ...
2495     2495      3  4645.714286  4651.428571   5.714286
2496     2496      3  4651.428571  4657.142857   5.714286
2497     2497      2  4616.000000  4624.000000   8.000000
2498     2498      2  4624.000000  4632.000000   8.000000
2499     2499      1  4608.000000  4624.000000  16.000000

[2500 rows x 5 columns]
algo not found
100
188.57142857142858
100
    task_id  VM_ID  Start_time  Finish_time  Exec_time
0         0      3    0.000000     5.714286   5.714286
1         1      4    0.000000     5.714286   5.714286
2         2      2    0.000000     8.000000   8.000000
3         3      2    8.000000    16.000000   8.000000
4         4      2   16.000000    24.000000   8.000000
..      ...    ...         ...          ...        ...
95       95      3  177.142857   182.857143   5.714286
96       96      4  177.142857   182.857143   5.714286
97       97      3  182.857143   188.571429   5.714286
98       98      4  182.857143   188.571429   5.714286
99       99      2  176.000000   184.000000   8.000000

[100 rows x 5 columns]
500
1072.0
500
     task_id  VM_ID   Start_time  Finish_time  Exec_time
0          0      3     0.000000     5.714286   5.714286
1          1      2     0.000000     8.000000   8.000000
2          2      4     0.000000     5.714286   5.714286
3          3      0     0.000000     5.714286   5.714286
4          4      3     5.714286    11.428571   5.714286
..       ...    ...          ...          ...        ...
495      495      2  1056.000000  1064.000000   8.000000
496      496      2  1064.000000  1072.000000   8.000000
497      497      4   634.285714   640.000000   5.714286
498      498      3  1057.142857  1062.857143   5.714286
499      499      3  1062.857143  1068.571429   5.714286

[500 rows x 5 columns]
1000
An exception occurred local variable 'start' referenced before assignment
1500
4880.0
1500
      task_id  VM_ID   Start_time  Finish_time  Exec_time
0           0      2     0.000000     8.000000   8.000000
1           1      3     0.000000     5.714286   5.714286
2           2      2     8.000000    16.000000   8.000000
3           3      2    16.000000    24.000000   8.000000
4           4      3     5.714286    11.428571   5.714286
...       ...    ...          ...          ...        ...
1495     1495      2  4872.000000  4880.000000   8.000000
1496     1496      3  2982.857143  2988.571429   5.714286
1497     1497      3  2988.571429  2994.285714   5.714286
1498     1498      4   342.857143   348.571429   5.714286
1499     1499      0   342.857143   348.571429   5.714286

[1500 rows x 5 columns]
2000
6568.0
2000
      task_id  VM_ID   Start_time  Finish_time  Exec_time
0           0      2     0.000000     8.000000   8.000000
1           1      1     0.000000    16.000000  16.000000
2           2      2     8.000000    16.000000   8.000000
3           3      3     0.000000     5.714286   5.714286
4           4      0     0.000000     5.714286   5.714286
...       ...    ...          ...          ...        ...
1995     1995      4  1148.571429  1154.285714   5.714286
1996     1996      2  6552.000000  6560.000000   8.000000
1997     1997      3  3228.571429  3234.285714   5.714286
1998     1998      3  3234.285714  3240.000000   5.714286
1999     1999      2  6560.000000  6568.000000   8.000000

[2000 rows x 5 columns]
2500
8720.0
2500
      task_id  VM_ID   Start_time  Finish_time  Exec_time
0           0      2     0.000000     8.000000   8.000000
1           1      3     0.000000     5.714286   5.714286
2           2      3     5.714286    11.428571   5.714286
3           3      1     0.000000    16.000000  16.000000
4           4      2     8.000000    16.000000   8.000000
...       ...    ...          ...          ...        ...
2495     2495      1  8688.000000  8704.000000  16.000000
2496     2496      2  8712.000000  8720.000000   8.000000
2497     2497      3  3731.428571  3737.142857   5.714286
2498     2498      0  3731.428571  3737.142857   5.714286
2499     2499      4  1200.000000  1205.714286   5.714286

[2500 rows x 5 columns]
algo not found
100
205.71428571428575
100
    task_id  VM_ID  Start_time  Finish_time  Exec_time
0         0      4    0.000000     5.714286   5.714286
1         1      2    0.000000     8.000000   8.000000
2         2      3    0.000000     5.714286   5.714286
3         3      2    8.000000    16.000000   8.000000
4         4      2   16.000000    24.000000   8.000000
..      ...    ...         ...          ...        ...
95       95      3  165.714286   171.428571   5.714286
96       96      4  200.000000   205.714286   5.714286
97       97      3  171.428571   177.142857   5.714286
98       98      2  184.000000   192.000000   8.000000
99       99      2  192.000000   200.000000   8.000000

[100 rows x 5 columns]
500
1028.5714285714246
500
     task_id  VM_ID   Start_time  Finish_time  Exec_time
0          0      2     0.000000     8.000000   8.000000
1          1      3     0.000000     5.714286   5.714286
2          2      3     5.714286    11.428571   5.714286
3          3      2     8.000000    16.000000   8.000000
4          4      2    16.000000    24.000000   8.000000
..       ...    ...          ...          ...        ...
495      495      4  1000.000000  1005.714286   5.714286
496      496      2   816.000000   824.000000   8.000000
497      497      3  1017.142857  1022.857143   5.714286
498      498      4  1005.714286  1011.428571   5.714286
499      499      3  1022.857143  1028.571429   5.714286

[500 rows x 5 columns]
1000
2034.2857142857217
1000
     task_id  VM_ID   Start_time  Finish_time  Exec_time
0          0      3     0.000000     5.714286   5.714286
1          1      4     0.000000     5.714286   5.714286
2          2      2     0.000000     8.000000   8.000000
3          3      3     5.714286    11.428571   5.714286
4          4      4     5.714286    11.428571   5.714286
..       ...    ...          ...          ...        ...
995      995      1  1056.000000  1072.000000  16.000000
996      996      3  2022.857143  2028.571429   5.714286
997      997      4  1994.285714  2000.000000   5.714286
998      998      3  2028.571429  2034.285714   5.714286
999      999      4  2000.000000  2005.714286   5.714286

[1000 rows x 5 columns]
1500
3005.714285714304
1500
      task_id  VM_ID   Start_time  Finish_time  Exec_time
0           0      3     0.000000     5.714286   5.714286
1           1      3     5.714286    11.428571   5.714286
2           2      0     5.714286    11.428571   5.714286
3           3      2     0.000000     8.000000   8.000000
4           4      4     0.000000     5.714286   5.714286
...       ...    ...          ...          ...        ...
1495     1495      2  2776.000000  2784.000000   8.000000
1496     1496      3  3000.000000  3005.714286   5.714286
1497     1497      4  2948.571429  2954.285714   5.714286
1498     1498      2  2784.000000  2792.000000   8.000000
1499     1499      4  2954.285714  2960.000000   5.714286

[1500 rows x 5 columns]
2000
3897.1428571428855
2000
      task_id  VM_ID   Start_time  Finish_time  Exec_time
0           0      4     0.000000     5.714286   5.714286
1           1      4     5.714286    11.428571   5.714286
2           2      4    11.428571    17.142857   5.714286
3           3      3     0.000000     5.714286   5.714286
4           4      1     0.000000    16.000000  16.000000
...       ...    ...          ...          ...        ...
1995     1995      4  3880.000000  3885.714286   5.714286
1996     1996      4  3885.714286  3891.428571   5.714286
1997     1997      3  3805.714286  3811.428571   5.714286
1998     1998      3  3811.428571  3817.142857   5.714286
1999     1999      4  3891.428571  3897.142857   5.714286

[2000 rows x 5 columns]
2500
4982.857142857113
2500
      task_id  VM_ID   Start_time  Finish_time  Exec_time
0           0      2     0.000000     8.000000   8.000000
1           1      3     0.000000     5.714286   5.714286
2           2      4     0.000000     5.714286   5.714286
3           3      3     5.714286    11.428571   5.714286
4           4      4     5.714286    11.428571   5.714286
...       ...    ...          ...          ...        ...
2495     2495      2  4712.000000  4720.000000   8.000000
2496     2496      3  4920.000000  4925.714286   5.714286
2497     2497      4  4965.714286  4971.428571   5.714286
2498     2498      4  4971.428571  4977.142857   5.714286
2499     2499      4  4977.142857  4982.857143   5.714286

[2500 rows x 5 columns]
100
240.0
100
    task_id  VM_ID  Start_time  Finish_time  Exec_time
0         0      2    0.000000     8.000000   8.000000
1         1      3    0.000000     5.714286   5.714286
2         2      4    0.000000     5.714286   5.714286
3         3      2    8.000000    16.000000   8.000000
4         4      3    5.714286    11.428571   5.714286
..      ...    ...         ...          ...        ...
95       95      3  165.714286   171.428571   5.714286
96       96      2  200.000000   208.000000   8.000000
97       97      3  171.428571   177.142857   5.714286
98       98      2  208.000000   216.000000   8.000000
99       99      2  216.000000   224.000000   8.000000

[100 rows x 5 columns]
500
2208.0
500
     task_id  VM_ID   Start_time  Finish_time  Exec_time
0          0      3     0.000000     5.714286   5.714286
1          1      4     0.000000     5.714286   5.714286
2          2      0     0.000000     5.714286   5.714286
3          3      4     5.714286    11.428571   5.714286
4          4      0     5.714286    11.428571   5.714286
..       ...    ...          ...          ...        ...
495      495      4  1102.857143  1108.571429   5.714286
496      496      2   648.000000   656.000000   8.000000
497      497      4  1108.571429  1114.285714   5.714286
498      498      4  1114.285714  1120.000000   5.714286
499      499      0  1114.285714  1120.000000   5.714286

[500 rows x 5 columns]
1000
An exception occurred local variable 'start' referenced before assignment
1500
7632.0
1500
      task_id  VM_ID   Start_time  Finish_time  Exec_time
0           0      2     0.000000     8.000000   8.000000
1           1      3     0.000000     5.714286   5.714286
2           2      3     5.714286    11.428571   5.714286
3           3      4     0.000000     5.714286   5.714286
4           4      2     8.000000    16.000000   8.000000
...       ...    ...          ...          ...        ...
1495     1495      1  7600.000000  7616.000000  16.000000
1496     1496      2  1552.000000  1560.000000   8.000000
1497     1497      3  1765.714286  1771.428571   5.714286
1498     1498      1  7616.000000  7632.000000  16.000000
1499     1499      4  2954.285714  2960.000000   5.714286

[1500 rows x 5 columns]
2000
10176.0
2000
      task_id  VM_ID   Start_time  Finish_time  Exec_time
0           0      4     0.000000     5.714286   5.714286
1           1      0     0.000000     5.714286   5.714286
2           2      4     5.714286    11.428571   5.714286
3           3      1    16.000000    32.000000  16.000000
4           4      0    16.000000    32.000000  16.000000
...       ...    ...          ...          ...        ...
1995     1995      4  4114.285714  4120.000000   5.714286
1996     1996      3  1920.000000  1925.714286   5.714286
1997     1997      2  2424.000000  2432.000000   8.000000
1998     1998      4  4120.000000  4125.714286   5.714286
1999     1999      4  4125.714286  4131.428571   5.714286

[2000 rows x 5 columns]
2500
13104.0
2500
      task_id  VM_ID   Start_time  Finish_time  Exec_time
0           0      2     0.000000     8.000000   8.000000
1           1      1     0.000000    16.000000  16.000000
2           2      0     0.000000    16.000000  16.000000

<ipython-input-8-e9652d172dbe>:97: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2_exe.insert(1, f,exe1)
<ipython-input-8-e9652d172dbe>:98: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2_start.insert(1, f,average_start)
<ipython-input-8-e9652d172dbe>:99: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2_finish.insert(1, f,average_finish)
<ipython-input-8-e9652d172dbe>:100: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2_aexe.insert(1, f,average_exe)
<ipython-input-8-e9652d172dbe>:101: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2_util.insert(1, f,utili1)
<ipython-input-8-e9652d172dbe>:102: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2_power.insert(1, f,power)

100
188.57142857142858
100
    task_id  VM_ID  Start_time  Finish_time  Exec_time
0         0      4    0.000000     5.714286   5.714286
1         1      2    0.000000     8.000000   8.000000
2         2      2    8.000000    16.000000   8.000000
3         3      1    0.000000    16.000000  16.000000
4         4      2   16.000000    24.000000   8.000000
..      ...    ...         ...          ...        ...
95       95      3  182.857143   188.571429   5.714286
96       96      4  165.714286   171.428571   5.714286
97       97      4  171.428571   177.142857   5.714286
98       98      4  177.142857   182.857143   5.714286
99       99      4  182.857143   188.571429   5.714286

[100 rows x 5 columns]
500
1079.9999999999966
500
     task_id  VM_ID   Start_time  Finish_time  Exec_time
0          0      2     0.000000     8.000000   8.000000
1          1      4     0.000000     5.714286   5.714286
2          2      2     8.000000    16.000000   8.000000
3          3      3     0.000000     5.714286   5.714286
4          4      3     5.714286    11.428571   5.714286
..       ...    ...          ...          ...        ...
495      495      1  1040.000000  1056.000000  16.000000
496      496      2  1040.000000  1048.000000   8.000000
497      497      2  1048.000000  1056.000000   8.000000
498      498      1  1056.000000  1072.000000  16.000000
499      499      2  1056.000000  1064.000000   8.000000

[500 rows x 5 columns]
1000
2592.0
1000
     task_id  VM_ID   Start_time  Finish_time  Exec_time
0          0      3     0.000000     5.714286   5.714286
1          1      2     0.000000     8.000000   8.000000
2          2      1     0.000000    16.000000  16.000000
3          3      2     8.000000    16.000000   8.000000
4          4      2    16.000000    24.000000   8.000000
..       ...    ...          ...          ...        ...
995      995      2  2576.000000  2584.000000   8.000000
996      996      3  2022.857143  2028.571429   5.714286
997      997      4   902.857143   908.571429   5.714286
998      998      1  2576.000000  2592.000000  16.000000
999      999      2  2584.000000  2592.000000   8.000000

[1000 rows x 5 columns]
1500
4672.0
1500
      task_id  VM_ID   Start_time  Finish_time  Exec_time
0           0      4     0.000000     5.714286   5.714286
1           1      4     5.714286    11.428571   5.714286
2           2      0     5.714286    11.428571   5.714286
3           3      2     0.000000     8.000000   8.000000
4           4      1    16.000000    32.000000  16.000000
...       ...    ...          ...          ...        ...
1495     1495      2  3800.000000  3808.000000   8.000000
1496     1496      3  2754.285714  2760.000000   5.714286
1497     1497      2  3808.000000  3816.000000   8.000000
1498     1498      3  2760.000000  2765.714286   5.714286
1499     1499      2  3816.000000  3824.000000   8.000000

[1500 rows x 5 columns]
2000
6768.0
2000
      task_id  VM_ID   Start_time  Finish_time  Exec_time
0           0      3     0.000000     5.714286   5.714286
1           1      3     5.714286    11.428571   5.714286
2           2      3    11.428571    17.142857   5.714286
3           3      1     0.000000    16.000000  16.000000
4           4      2     0.000000     8.000000   8.000000
...       ...    ...          ...          ...        ...
1995     1995      3  3685.714286  3691.428571   5.714286
1996     1996      2  5048.000000  5056.000000   8.000000
1997     1997      2  5056.000000  5064.000000   8.000000
1998     1998      4  1697.142857  1702.857143   5.714286
1999     1999      1  6752.000000  6768.000000  16.000000

[2000 rows x 5 columns]
2500
9056.0
2500
      task_id  VM_ID   Start_time  Finish_time  Exec_time
0           0      1     0.000000    16.000000  16.000000
1           1      2     0.000000     8.000000   8.000000
2           2      4     0.000000     5.714286   5.714286
3           3      4     5.714286    11.428571   5.714286
4           4      3     0.000000     5.714286   5.714286
...       ...    ...          ...          ...        ...
2495     2495      4  2171.428571  2177.142857   5.714286
2496     2496      4  2177.142857  2182.857143   5.714286
2497     2497      2  6112.000000  6120.000000   8.000000
2498     2498      0  6112.000000  6120.000000   8.000000
2499     2499      4  2182.857143  2188.571429   5.714286

[2500 rows x 5 columns]

<ipython-input-8-e9652d172dbe>:97: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2_exe.insert(1, f,exe1)
<ipython-input-8-e9652d172dbe>:98: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2_start.insert(1, f,average_start)
<ipython-input-8-e9652d172dbe>:99: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2_finish.insert(1, f,average_finish)
<ipython-input-8-e9652d172dbe>:100: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2_aexe.insert(1, f,average_exe)
<ipython-input-8-e9652d172dbe>:101: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2_util.insert(1, f,utili1)
<ipython-input-8-e9652d172dbe>:102: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2_power.insert(1, f,power)

100
An exception occurred local variable 'start' referenced before assignment
500
931.4285714285683
500
     task_id  VM_ID  Start_time  Finish_time  Exec_time
0          0      2    0.000000     8.000000   8.000000
1          1      1    0.000000    16.000000  16.000000
2          2      3    0.000000     5.714286   5.714286
3          3      3    5.714286    11.428571   5.714286
4          4      2    8.000000    16.000000   8.000000
..       ...    ...         ...          ...        ...
495      495      1  896.000000   912.000000  16.000000
496      496      3  920.000000   925.714286   5.714286
497      497      3  925.714286   931.428571   5.714286
498      498      0  925.714286   931.428571   5.714286
499      499      2  920.000000   928.000000   8.000000

[500 rows x 5 columns]
1000
1874.28571428572
1000
     task_id  VM_ID   Start_time  Finish_time  Exec_time
0          0      2     0.000000     8.000000   8.000000
1          1      2     8.000000    16.000000   8.000000
2          2      2    16.000000    24.000000   8.000000
3          3      3     0.000000     5.714286   5.714286
4          4      1     0.000000    16.000000  16.000000
..       ...    ...          ...          ...        ...
995      995      4  1862.857143  1868.571429   5.714286
996      996      1  1744.000000  1760.000000  16.000000
997      997      4  1868.571429  1874.285714   5.714286
998      998      1  1760.000000  1776.000000  16.000000
999      999      2  1864.000000  1872.000000   8.000000

[1000 rows x 5 columns]
1500
2857.1428571428737
1500
      task_id  VM_ID   Start_time  Finish_time  Exec_time
0           0      3     0.000000     5.714286   5.714286
1           1      4     0.000000     5.714286   5.714286
2           2      3     5.714286    11.428571   5.714286
3           3      2     0.000000     8.000000   8.000000
4           4      3    11.428571    17.142857   5.714286
...       ...    ...          ...          ...        ...
1495     1495      2  2792.000000  2800.000000   8.000000
1496     1496      4  2845.714286  2851.428571   5.714286
1497     1497      1  2464.000000  2480.000000  16.000000
1498     1498      4  2851.428571  2857.142857   5.714286
1499     1499      2  2800.000000  2808.000000   8.000000

[1500 rows x 5 columns]
2000
3742.8571428571695
2000
      task_id  VM_ID   Start_time  Finish_time  Exec_time
0           0      3     0.000000     5.714286   5.714286
1           1      4     0.000000     5.714286   5.714286
2           2      3     5.714286    11.428571   5.714286
3           3      2     0.000000     8.000000   8.000000
4           4      2     8.000000    16.000000   8.000000
...       ...    ...          ...          ...        ...
1995     1995      1  3648.000000  3664.000000  16.000000
1996     1996      0  3648.000000  3664.000000  16.000000
1997     1997      4  3737.142857  3742.857143   5.714286
1998     1998      3  3725.714286  3731.428571   5.714286
1999     1999      3  3731.428571  3737.142857   5.714286

[2000 rows x 5 columns]
2500
4862.857142857121
2500
      task_id  VM_ID   Start_time  Finish_time  Exec_time
0           0      2     0.000000     8.000000   8.000000
1           1      4     0.000000     5.714286   5.714286
2           2      4     5.714286    11.428571   5.714286
3           3      3     0.000000     5.714286   5.714286
4           4      3     5.714286    11.428571   5.714286
...       ...    ...          ...          ...        ...
2495     2495      2  4736.000000  4744.000000   8.000000
2496     2496      3  4680.000000  4685.714286   5.714286
2497     2497      3  4685.714286  4691.428571   5.714286
2498     2498      3  4691.428571  4697.142857   5.714286
2499     2499      4  4857.142857  4862.857143   5.714286

[2500 rows x 5 columns]
algo not found
100
208.0
100
    task_id  VM_ID  Start_time  Finish_time  Exec_time
0         0      4    0.000000     5.714286   5.714286
1         1      4    5.714286    11.428571   5.714286
2         2      3    0.000000     5.714286   5.714286
3         3      2    0.000000     8.000000   8.000000
4         4      3    5.714286    11.428571   5.714286
..      ...    ...         ...          ...        ...
95       95      3  154.285714   160.000000   5.714286
96       96      4  182.857143   188.571429   5.714286
97       97      4  188.571429   194.285714   5.714286
98       98      4  194.285714   200.000000   5.714286
99       99      4  200.000000   205.714286   5.714286

[100 rows x 5 columns]
500
1088.0
500
     task_id  VM_ID  Start_time  Finish_time  Exec_time
0          0      4    0.000000     5.714286   5.714286
1          1      0    0.000000     5.714286   5.714286
2          2      3    0.000000     5.714286   5.714286
3          3      3    5.714286    11.428571   5.714286
4          4      4    5.714286    11.428571   5.714286
..       ...    ...         ...          ...        ...
495      495      3  760.000000   765.714286   5.714286
496      496      2  848.000000   856.000000   8.000000
497      497      3  765.714286   771.428571   5.714286
498      498      2  856.000000   864.000000   8.000000
499      499      3  771.428571   777.142857   5.714286

[500 rows x 5 columns]
1000
2240.0
1000
     task_id  VM_ID   Start_time  Finish_time  Exec_time
0          0      4     0.000000     5.714286   5.714286
1          1      2     0.000000     8.000000   8.000000
2          2      3     0.000000     5.714286   5.714286
3          3      4     5.714286    11.428571   5.714286
4          4      1     0.000000    16.000000  16.000000
..       ...    ...          ...          ...        ...
995      995      4  2194.285714  2200.000000   5.714286
996      996      4  2200.000000  2205.714286   5.714286
997      997      3  1411.428571  1417.142857   5.714286
998      998      4  2205.714286  2211.428571   5.714286
999      999      4  2211.428571  2217.142857   5.714286

[1000 rows x 5 columns]
1500
3488.0
1500
      task_id  VM_ID   Start_time  Finish_time  Exec_time
0           0      2     0.000000     8.000000   8.000000
1           1      4     0.000000     5.714286   5.714286
2           2      2     8.000000    16.000000   8.000000
3           3      4     5.714286    11.428571   5.714286
4           4      2    16.000000    24.000000   8.000000
...       ...    ...          ...          ...        ...
1495     1495      4  3440.000000  3445.714286   5.714286
1496     1496      0  3440.000000  3445.714286   5.714286
1497     1497      2  2608.000000  2616.000000   8.000000
1498     1498      3  2000.000000  2005.714286   5.714286
1499     1499      3  2005.714286  2011.428571   5.714286

[1500 rows x 5 columns]
2000
4752.0
2000
      task_id  VM_ID   Start_time  Finish_time  Exec_time
0           0      4     0.000000     5.714286   5.714286
1           1      3     0.000000     5.714286   5.714286
2           2      4     5.714286    11.428571   5.714286
3           3      2     0.000000     8.000000   8.000000
4           4      3     5.714286    11.428571   5.714286
...       ...    ...          ...          ...        ...
1995     1995      4  4725.714286  4731.428571   5.714286
1996     1996      0  4725.714286  4731.428571   5.714286
1997     1997      4  4731.428571  4737.142857   5.714286
1998     1998      2  3392.000000  3400.000000   8.000000
1999     1999      4  4737.142857  4742.857143   5.714286

[2000 rows x 5 columns]
2500
5968.0
2500
      task_id  VM_ID   Start_time  Finish_time  Exec_time
0           0      4     0.000000     5.714286   5.714286
1           1      2     0.000000     8.000000   8.000000
2           2      2     8.000000    16.000000   8.000000
3           3      2    16.000000    24.000000   8.000000
4           4      2    24.000000    32.000000   8.000000
...       ...    ...          ...          ...        ...
2495     2495      2  4240.000000  4248.000000   8.000000
2496     2496      3  3268.571429  3274.285714   5.714286
2497     2497      1  5936.000000  5952.000000  16.000000
2498     2498      3  3274.285714  3280.000000   5.714286
2499     2499      1  5952.000000  5968.000000  16.000000

[2500 rows x 5 columns]

<ipython-input-8-e9652d172dbe>:97: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2_exe.insert(1, f,exe1)
<ipython-input-8-e9652d172dbe>:98: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2_start.insert(1, f,average_start)
<ipython-input-8-e9652d172dbe>:99: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2_finish.insert(1, f,average_finish)
<ipython-input-8-e9652d172dbe>:100: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2_aexe.insert(1, f,average_exe)
<ipython-input-8-e9652d172dbe>:101: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2_util.insert(1, f,utili1)
<ipython-input-8-e9652d172dbe>:102: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2_power.insert(1, f,power)

100
368.0
100
    task_id  VM_ID  Start_time  Finish_time  Exec_time
0         0      3    0.000000     5.714286   5.714286
1         1      1    0.000000    16.000000  16.000000
2         2      2    0.000000     8.000000   8.000000
3         3      2    8.000000    16.000000   8.000000
4         4      2   16.000000    24.000000   8.000000
..      ...    ...         ...          ...        ...
95       95      4   68.571429    74.285714   5.714286
96       96      1  336.000000   352.000000  16.000000
97       97      2  256.000000   264.000000   8.000000
98       98      0  256.000000   264.000000   8.000000
99       99      4   74.285714    80.000000   5.714286

[100 rows x 5 columns]
500
2416.0
500
     task_id  VM_ID   Start_time  Finish_time  Exec_time
0          0      2     0.000000     8.000000   8.000000
1          1      4     0.000000     5.714286   5.714286
2          2      2     8.000000    16.000000   8.000000
3          3      1     0.000000    16.000000  16.000000
4          4      1    16.000000    32.000000  16.000000
..       ...    ...          ...          ...        ...
495      495      3   748.571429   754.285714   5.714286
496      496      3   754.285714   760.000000   5.714286
497      497      2  1224.000000  1232.000000   8.000000
498      498      2  1232.000000  1240.000000   8.000000
499      499      1  2400.000000  2416.000000  16.000000

[500 rows x 5 columns]
1000
5472.0
1000
     task_id  VM_ID   Start_time  Finish_time  Exec_time
0          0      3     0.000000     5.714286   5.714286
1          1      0     0.000000     5.714286   5.714286
2          2      3     5.714286    11.428571   5.714286
3          3      2     0.000000     8.000000   8.000000
4          4      3    11.428571    17.142857   5.714286
..       ...    ...          ...          ...        ...
995      995      1  5424.000000  5440.000000  16.000000
996      996      3  1440.000000  1445.714286   5.714286
997      997      1  5440.000000  5456.000000  16.000000
998      998      3  1445.714286  1451.428571   5.714286
999      999      1  5456.000000  5472.000000  16.000000

[1000 rows x 5 columns]
1500
8384.0
1500
      task_id  VM_ID   Start_time  Finish_time  Exec_time
0           0      2     0.000000     8.000000   8.000000
1           1      3     0.000000     5.714286   5.714286
2           2      2     8.000000    16.000000   8.000000
3           3      2    16.000000    24.000000   8.000000
4           4      4     0.000000     5.714286   5.714286
...       ...    ...          ...          ...        ...
1495     1495      4  1057.142857  1062.857143   5.714286
1496     1496      1  8368.000000  8384.000000  16.000000
1497     1497      3  2148.571429  2154.285714   5.714286
1498     1498      3  2154.285714  2160.000000   5.714286
1499     1499      4  1062.857143  1068.571429   5.714286

[1500 rows x 5 columns]
2000
11428.571428571475
2000
      task_id  VM_ID    Start_time   Finish_time  Exec_time
0           0      4      0.000000      5.714286   5.714286
1           1      4      5.714286     11.428571   5.714286
2           2      4     11.428571     17.142857   5.714286
3           3      4     17.142857     22.857143   5.714286
4           4      4     22.857143     28.571429   5.714286
...       ...    ...           ...           ...        ...
1995     1995      4  11400.000000  11405.714286   5.714286
1996     1996      4  11405.714286  11411.428571   5.714286
1997     1997      4  11411.428571  11417.142857   5.714286
1998     1998      4  11417.142857  11422.857143   5.714286
1999     1999      4  11422.857143  11428.571429   5.714286

[2000 rows x 5 columns]
2500
14256.0
2500
      task_id  VM_ID   Start_time  Finish_time  Exec_time
0           0      1     0.000000    16.000000  16.000000
1           1      3     0.000000     5.714286   5.714286
2           2      2     0.000000     8.000000   8.000000
3           3      0     0.000000     8.000000   8.000000
4           4      2     8.000000    16.000000   8.000000
...       ...    ...          ...          ...        ...
2495     2495      3  3748.571429  3754.285714   5.714286
2496     2496      4  1794.285714  1800.000000   5.714286
2497     2497      2  5080.000000  5088.000000   8.000000
2498     2498      2  5088.000000  5096.000000   8.000000
2499     2499      0  5088.000000  5096.000000   8.000000

[2500 rows x 5 columns]

<ipython-input-8-e9652d172dbe>:97: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2_exe.insert(1, f,exe1)
<ipython-input-8-e9652d172dbe>:98: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2_start.insert(1, f,average_start)
<ipython-input-8-e9652d172dbe>:99: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2_finish.insert(1, f,average_finish)
<ipython-input-8-e9652d172dbe>:100: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2_aexe.insert(1, f,average_exe)
<ipython-input-8-e9652d172dbe>:101: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2_util.insert(1, f,utili1)
<ipython-input-8-e9652d172dbe>:102: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2_power.insert(1, f,power)

100
188.57142857142858
100
    task_id  VM_ID  Start_time  Finish_time  Exec_time
0         0      1    0.000000    16.000000  16.000000
1         1      3    0.000000     5.714286   5.714286
2         2      4    0.000000     5.714286   5.714286
3         3      4    5.714286    11.428571   5.714286
4         4      3    5.714286    11.428571   5.714286
..      ...    ...         ...          ...        ...
95       95      1  160.000000   176.000000  16.000000
96       96      2  176.000000   184.000000   8.000000
97       97      4  182.857143   188.571429   5.714286
98       98      3  177.142857   182.857143   5.714286
99       99      3  182.857143   188.571429   5.714286

[100 rows x 5 columns]
500
1064.0
500
     task_id  VM_ID   Start_time  Finish_time  Exec_time
0          0      2     0.000000     8.000000   8.000000
1          1      3     0.000000     5.714286   5.714286
2          2      3     5.714286    11.428571   5.714286
3          3      2     8.000000    16.000000   8.000000
4          4      2    16.000000    24.000000   8.000000
..       ...    ...          ...          ...        ...
495      495      3  1051.428571  1057.142857   5.714286
496      496      1   976.000000   992.000000  16.000000
497      497      1   992.000000  1008.000000  16.000000
498      498      0   992.000000  1008.000000  16.000000
499      499      2  1056.000000  1064.000000   8.000000

[500 rows x 5 columns]
1000
2368.0
1000
     task_id  VM_ID   Start_time  Finish_time  Exec_time
0          0      2     0.000000     8.000000   8.000000
1          1      3     0.000000     5.714286   5.714286
2          2      4     0.000000     5.714286   5.714286
3          3      1     0.000000    16.000000  16.000000
4          4      3     5.714286    11.428571   5.714286
..       ...    ...          ...          ...        ...
995      995      3  2154.285714  2160.000000   5.714286
996      996      4  1022.857143  1028.571429   5.714286
997      997      2  2336.000000  2344.000000   8.000000
998      998      1  2352.000000  2368.000000  16.000000
999      999      2  2344.000000  2352.000000   8.000000

[1000 rows x 5 columns]
1500
An exception occurred local variable 'start' referenced before assignment
2000
6096.0
2000
      task_id  VM_ID   Start_time  Finish_time  Exec_time
0           0      1     0.000000    16.000000  16.000000
1           1      2     0.000000     8.000000   8.000000
2           2      3     0.000000     5.714286   5.714286
3           3      3     5.714286    11.428571   5.714286
4           4      0     5.714286    11.428571   5.714286
...       ...    ...          ...          ...        ...
1995     1995      2  5240.000000  5248.000000   8.000000
1996     1996      4  1862.857143  1868.571429   5.714286
1997     1997      3  3617.142857  3622.857143   5.714286
1998     1998      4  1868.571429  1874.285714   5.714286
1999     1999      2  5248.000000  5256.000000   8.000000

[2000 rows x 5 columns]
2500
8000.0
2500
      task_id  VM_ID   Start_time  Finish_time  Exec_time
0           0      3     0.000000     5.714286   5.714286
1           1      4     0.000000     5.714286   5.714286
2           2      1     0.000000    16.000000  16.000000
3           3      2     0.000000     8.000000   8.000000
4           4      3     5.714286    11.428571   5.714286
...       ...    ...          ...          ...        ...
2495     2495      1  7968.000000  7984.000000  16.000000
2496     2496      3  4565.714286  4571.428571   5.714286
2497     2497      3  4571.428571  4577.142857   5.714286
2498     2498      1  7984.000000  8000.000000  16.000000
2499     2499      3  4577.142857  4582.857143   5.714286

[2500 rows x 5 columns]
algo not found
100
An exception occurred local variable 'start' referenced before assignment
500
1552.0
500
     task_id  VM_ID   Start_time  Finish_time  Exec_time
0          0      2     0.000000     8.000000   8.000000
1          1      0     0.000000     8.000000   8.000000
2          2      0     0.000000     8.000000   8.000000
3          3      3     0.000000     5.714286   5.714286
4          4      2     8.000000    16.000000   8.000000
..       ...    ...          ...          ...        ...
495      495      2  1488.000000  1496.000000   8.000000
496      496      3   617.142857   622.857143   5.714286
497      497      2  1496.000000  1504.000000   8.000000
498      498      2  1504.000000  1512.000000   8.000000
499      499      3   622.857143   628.571429   5.714286

[500 rows x 5 columns]
1000
An exception occurred local variable 'start' referenced before assignment
1500
6656.0
1500
      task_id  VM_ID   Start_time  Finish_time  Exec_time
0           0      3     0.000000     5.714286   5.714286
1           1      4     0.000000     5.714286   5.714286
2           2      1     0.000000    16.000000  16.000000
3           3      4     5.714286    11.428571   5.714286
4           4      4    11.428571    17.142857   5.714286
...       ...    ...          ...          ...        ...
1495     1495      2  4008.000000  4016.000000   8.000000
1496     1496      4  1491.428571  1497.142857   5.714286
1497     1497      2  4016.000000  4024.000000   8.000000
1498     1498      4  1497.142857  1502.857143   5.714286
1499     1499      4  1502.857143  1508.571429   5.714286

[1500 rows x 5 columns]
2000
9120.0
2000
      task_id  VM_ID   Start_time  Finish_time  Exec_time
0           0      3     0.000000     5.714286   5.714286
1           1      1     0.000000    16.000000  16.000000
2           2      2     0.000000     8.000000   8.000000
3           3      3     5.714286    11.428571   5.714286
4           4      2     8.000000    16.000000   8.000000
...       ...    ...          ...          ...        ...
1995     1995      4  1880.000000  1885.714286   5.714286
1996     1996      4  1885.714286  1891.428571   5.714286
1997     1997      4  1891.428571  1897.142857   5.714286
1998     1998      3  2565.714286  2571.428571   5.714286
1999     1999      0  2565.714286  2571.428571   5.714286

[2000 rows x 5 columns]
2500
12048.0
2500
      task_id  VM_ID    Start_time   Finish_time  Exec_time
0           0      2      0.000000      8.000000   8.000000
1           1      1      0.000000     16.000000  16.000000
2           2      2      8.000000     16.000000   8.000000
3           3      2     16.000000     24.000000   8.000000
4           4      0     16.000000     24.000000   8.000000
...       ...    ...           ...           ...        ...
2495     2495      3   2960.000000   2965.714286   5.714286
2496     2496      1  12032.000000  12048.000000  16.000000
2497     2497      4   2502.857143   2508.571429   5.714286
2498     2498      3   2965.714286   2971.428571   5.714286
2499     2499      2   6296.000000   6304.000000   8.000000

[2500 rows x 5 columns]
algo not found
100
304.0
100
    task_id  VM_ID  Start_time  Finish_time  Exec_time
0         0      2    0.000000     8.000000   8.000000
1         1      3    0.000000     5.714286   5.714286
2         2      2    8.000000    16.000000   8.000000
3         3      3    5.714286    11.428571   5.714286
4         4      3   11.428571    17.142857   5.714286
..      ...    ...         ...          ...        ...
95       95      3  211.428571   217.142857   5.714286
96       96      3  217.142857   222.857143   5.714286
97       97      2  288.000000   296.000000   8.000000
98       98      2  296.000000   304.000000   8.000000
99       99      1  288.000000   304.000000  16.000000

[100 rows x 5 columns]
500
1824.0
500
     task_id  VM_ID   Start_time  Finish_time  Exec_time
0          0      2     0.000000     8.000000   8.000000
1          1      3     0.000000     5.714286   5.714286
2          2      4     0.000000     5.714286   5.714286
3          3      2     8.000000    16.000000   8.000000
4          4      3     5.714286    11.428571   5.714286
..       ...    ...          ...          ...        ...
495      495      3   811.428571   817.142857   5.714286
496      496      1  1808.000000  1824.000000  16.000000
497      497      4    74.285714    80.000000   5.714286
498      498      2  1816.000000  1824.000000   8.000000
499      499      3   817.142857   822.857143   5.714286

[500 rows x 5 columns]
1000
3600.0
1000
     task_id  VM_ID  Start_time  Finish_time  Exec_time
0          0      2         0.0     8.000000   8.000000
1          1      2         8.0    16.000000   8.000000
2          2      4         0.0     5.714286   5.714286
3          3      3         0.0     5.714286   5.714286
4          4      2        16.0    24.000000   8.000000
..       ...    ...         ...          ...        ...
995      995      1      3552.0  3568.000000  16.000000
996      996      2      3584.0  3592.000000   8.000000
997      997      0      3584.0  3592.000000   8.000000
998      998      1      3584.0  3600.000000  16.000000
999      999      2      3592.0  3600.000000   8.000000

[1000 rows x 5 columns]
1500
5552.0
1500
      task_id  VM_ID   Start_time  Finish_time  Exec_time
0           0      1     0.000000    16.000000  16.000000
1           1      2     0.000000     8.000000   8.000000
2           2      2     8.000000    16.000000   8.000000
3           3      2    16.000000    24.000000   8.000000
4           4      2    24.000000    32.000000   8.000000
...       ...    ...          ...          ...        ...
1495     1495      3  2422.857143  2428.571429   5.714286
1496     1496      2  5480.000000  5488.000000   8.000000
1497     1497      4   228.571429   234.285714   5.714286
1498     1498      1  5536.000000  5552.000000  16.000000
1499     1499      3  2428.571429  2434.285714   5.714286

[1500 rows x 5 columns]
2000
7520.0
2000
      task_id  VM_ID   Start_time  Finish_time  Exec_time
0           0      2     0.000000     8.000000   8.000000
1           1      3     0.000000     5.714286   5.714286
2           2      3     5.714286    11.428571   5.714286
3           3      3    11.428571    17.142857   5.714286
4           4      2     8.000000    16.000000   8.000000
...       ...    ...          ...          ...        ...
1995     1995      2  7488.000000  7496.000000   8.000000
1996     1996      2  7496.000000  7504.000000   8.000000
1997     1997      3  3320.000000  3325.714286   5.714286
1998     1998      3  3325.714286  3331.428571   5.714286
1999     1999      3  3331.428571  3337.142857   5.714286

[2000 rows x 5 columns]
2500
9680.0
2500
      task_id  VM_ID   Start_time  Finish_time  Exec_time
0           0      2     0.000000     8.000000   8.000000
1           1      2     8.000000    16.000000   8.000000
2           2      2    16.000000    24.000000   8.000000
3           3      3     0.000000     5.714286   5.714286
4           4      3     5.714286    11.428571   5.714286
...       ...    ...          ...          ...        ...
2495     2495      1  9616.000000  9632.000000  16.000000
2496     2496      1  9632.000000  9648.000000  16.000000
2497     2497      1  9648.000000  9664.000000  16.000000
2498     2498      2  9656.000000  9664.000000   8.000000
2499     2499      1  9664.000000  9680.000000  16.000000

[2500 rows x 5 columns]

<ipython-input-8-e9652d172dbe>:97: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2_exe.insert(1, f,exe1)
<ipython-input-8-e9652d172dbe>:98: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2_start.insert(1, f,average_start)
<ipython-input-8-e9652d172dbe>:99: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2_finish.insert(1, f,average_finish)
<ipython-input-8-e9652d172dbe>:100: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2_aexe.insert(1, f,average_exe)
<ipython-input-8-e9652d172dbe>:101: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2_util.insert(1, f,utili1)
<ipython-input-8-e9652d172dbe>:102: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2_power.insert(1, f,power)

100
240.0
100
    task_id  VM_ID  Start_time  Finish_time  Exec_time
0         0      3    0.000000     5.714286   5.714286
1         1      3    5.714286    11.428571   5.714286
2         2      2    0.000000     8.000000   8.000000
3         3      3   11.428571    17.142857   5.714286
4         4      3   17.142857    22.857143   5.714286
..      ...    ...         ...          ...        ...
95       95      2  224.000000   232.000000   8.000000
96       96      3  188.571429   194.285714   5.714286
97       97      3  194.285714   200.000000   5.714286
98       98      2  232.000000   240.000000   8.000000
99       99      4  108.571429   114.285714   5.714286

[100 rows x 5 columns]
500
1744.0
500
     task_id  VM_ID   Start_time  Finish_time  Exec_time
0          0      2     0.000000     8.000000   8.000000
1          1      2     8.000000    16.000000   8.000000
2          2      3     0.000000     5.714286   5.714286
3          3      2    16.000000    24.000000   8.000000
4          4      2    24.000000    32.000000   8.000000
..       ...    ...          ...          ...        ...
495      495      2  1736.000000  1744.000000   8.000000
496      496      3   868.571429   874.285714   5.714286
497      497      4    97.142857   102.857143   5.714286
498      498      3   874.285714   880.000000   5.714286
499      499      3   880.000000   885.714286   5.714286

[500 rows x 5 columns]
1000
3664.0
1000
     task_id  VM_ID   Start_time  Finish_time  Exec_time
0          0      1     0.000000    16.000000  16.000000
1          1      3     0.000000     5.714286   5.714286
2          2      1    16.000000    32.000000  16.000000
3          3      2     0.000000     8.000000   8.000000
4          4      3     5.714286    11.428571   5.714286
..       ...    ...          ...          ...        ...
995      995      2  3656.000000  3664.000000   8.000000
996      996      3  1520.000000  1525.714286   5.714286
997      997      3  1525.714286  1531.428571   5.714286
998      998      3  1531.428571  1537.142857   5.714286
999      999      3  1537.142857  1542.857143   5.714286

[1000 rows x 5 columns]
1500
5648.0
1500
      task_id  VM_ID   Start_time  Finish_time  Exec_time
0           0      2     0.000000     8.000000   8.000000
1           1      2     8.000000    16.000000   8.000000
2           2      2    16.000000    24.000000   8.000000
3           3      3     0.000000     5.714286   5.714286
4           4      1     0.000000    16.000000  16.000000
...       ...    ...          ...          ...        ...
1495     1495      3  2177.142857  2182.857143   5.714286
1496     1496      1  5616.000000  5632.000000  16.000000
1497     1497      3  2182.857143  2188.571429   5.714286
1498     1498      1  5632.000000  5648.000000  16.000000
1499     1499      3  2188.571429  2194.285714   5.714286

[1500 rows x 5 columns]
2000
7648.0
2000
      task_id  VM_ID   Start_time  Finish_time  Exec_time
0           0      4     0.000000     5.714286   5.714286
1           1      2     0.000000     8.000000   8.000000
2           2      2     8.000000    16.000000   8.000000
3           3      2    16.000000    24.000000   8.000000
4           4      3     0.000000     5.714286   5.714286
...       ...    ...          ...          ...        ...
1995     1995      1  7616.000000  7632.000000  16.000000
1996     1996      2  7632.000000  7640.000000   8.000000
1997     1997      4   731.428571   737.142857   5.714286
1998     1998      2  7640.000000  7648.000000   8.000000
1999     1999      1  7632.000000  7648.000000  16.000000

[2000 rows x 5 columns]
2500
9696.0
2500
      task_id  VM_ID  Start_time  Finish_time  Exec_time
0           0      2         0.0          8.0        8.0
1           1      2         8.0         16.0        8.0
2           2      1         0.0         16.0       16.0
3           3      1        16.0         32.0       16.0
4           4      2        16.0         24.0        8.0
...       ...    ...         ...          ...        ...
2495     2495      2      9656.0       9664.0        8.0
2496     2496      2      9664.0       9672.0        8.0
2497     2497      2      9672.0       9680.0        8.0
2498     2498      2      9680.0       9688.0        8.0
2499     2499      2      9688.0       9696.0        8.0

[2500 rows x 5 columns]
100

<ipython-input-8-e9652d172dbe>:97: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2_exe.insert(1, f,exe1)
<ipython-input-8-e9652d172dbe>:98: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2_start.insert(1, f,average_start)
<ipython-input-8-e9652d172dbe>:99: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2_finish.insert(1, f,average_finish)
<ipython-input-8-e9652d172dbe>:100: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2_aexe.insert(1, f,average_exe)
<ipython-input-8-e9652d172dbe>:101: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2_util.insert(1, f,utili1)
<ipython-input-8-e9652d172dbe>:102: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2_power.insert(1, f,power)

371.4285714285717
100
    task_id  VM_ID  Start_time  Finish_time  Exec_time
0         0      2    0.000000     8.000000   8.000000
1         1      2    8.000000    16.000000   8.000000
2         2      4    0.000000     5.714286   5.714286
3         3      4    5.714286    11.428571   5.714286
4         4      4   11.428571    17.142857   5.714286
..      ...    ...         ...          ...        ...
95       95      4  360.000000   365.714286   5.714286
96       96      2  112.000000   120.000000   8.000000
97       97      4  365.714286   371.428571   5.714286
98       98      2  120.000000   128.000000   8.000000
99       99      2  128.000000   136.000000   8.000000

[100 rows x 5 columns]
500
1794.285714285719
500
     task_id  VM_ID   Start_time  Finish_time  Exec_time
0          0      3     0.000000     5.714286   5.714286
1          1      4     0.000000     5.714286   5.714286
2          2      4     5.714286    11.428571   5.714286
3          3      4    11.428571    17.142857   5.714286
4          4      4    17.142857    22.857143   5.714286
..       ...    ...          ...          ...        ...
495      495      4  1777.142857  1782.857143   5.714286
496      496      0  1777.142857  1782.857143   5.714286
497      497      4  1782.857143  1788.571429   5.714286
498      498      4  1788.571429  1794.285714   5.714286
499      499      0  1788.571429  1794.285714   5.714286

[500 rows x 5 columns]
1000
3428.5714285714516
1000
     task_id  VM_ID   Start_time  Finish_time  Exec_time
0          0      4     0.000000     5.714286   5.714286
1          1      2     0.000000     8.000000   8.000000
2          2      4     5.714286    11.428571   5.714286
3          3      2     8.000000    16.000000   8.000000
4          4      3     0.000000     5.714286   5.714286
..       ...    ...          ...          ...        ...
995      995      4  3411.428571  3417.142857   5.714286
996      996      0  3411.428571  3417.142857   5.714286
997      997      3  1097.142857  1102.857143   5.714286
998      998      4  3417.142857  3422.857143   5.714286
999      999      4  3422.857143  3428.571429   5.714286

[1000 rows x 5 columns]
1500
5422.857142857083
1500
      task_id  VM_ID   Start_time  Finish_time  Exec_time
0           0      4     0.000000     5.714286   5.714286
1           1      3     0.000000     5.714286   5.714286
2           2      2     0.000000     8.000000   8.000000
3           3      4     5.714286    11.428571   5.714286
4           4      4    11.428571    17.142857   5.714286
...       ...    ...          ...          ...        ...
1495     1495      2  1440.000000  1448.000000   8.000000
1496     1496      4  5405.714286  5411.428571   5.714286
1497     1497      4  5411.428571  5417.142857   5.714286
1498     1498      4  5417.142857  5422.857143   5.714286
1499     1499      3  1542.857143  1548.571429   5.714286

[1500 rows x 5 columns]
2000
7017.142857142689
2000
      task_id  VM_ID   Start_time  Finish_time  Exec_time
0           0      4     0.000000     5.714286   5.714286
1           1      3     0.000000     5.714286   5.714286
2           2      4     5.714286    11.428571   5.714286
3           3      4    11.428571    17.142857   5.714286
4           4      4    17.142857    22.857143   5.714286
...       ...    ...          ...          ...        ...
1995     1995      4  7000.000000  7005.714286   5.714286
1996     1996      4  7005.714286  7011.428571   5.714286
1997     1997      3  2137.142857  2142.857143   5.714286
1998     1998      2  1984.000000  1992.000000   8.000000
1999     1999      4  7011.428571  7017.142857   5.714286

[2000 rows x 5 columns]
2500
8748.571428571231
2500
      task_id  VM_ID   Start_time  Finish_time  Exec_time
0           0      3     0.000000     5.714286   5.714286
1           1      2     0.000000     8.000000   8.000000
2           2      4     0.000000     5.714286   5.714286
3           3      3     5.714286    11.428571   5.714286
4           4      4     5.714286    11.428571   5.714286
...       ...    ...          ...          ...        ...
2495     2495      3  2771.428571  2777.142857   5.714286
2496     2496      4  8725.714286  8731.428571   5.714286
2497     2497      4  8731.428571  8737.142857   5.714286
2498     2498      4  8737.142857  8742.857143   5.714286
2499     2499      4  8742.857143  8748.571429   5.714286

[2500 rows x 5 columns]

<ipython-input-8-e9652d172dbe>:97: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2_exe.insert(1, f,exe1)
<ipython-input-8-e9652d172dbe>:98: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2_start.insert(1, f,average_start)
<ipython-input-8-e9652d172dbe>:99: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2_finish.insert(1, f,average_finish)
<ipython-input-8-e9652d172dbe>:100: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2_aexe.insert(1, f,average_exe)
<ipython-input-8-e9652d172dbe>:101: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2_util.insert(1, f,utili1)
<ipython-input-8-e9652d172dbe>:102: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2_power.insert(1, f,power)

100
188.57142857142858
100
    task_id  VM_ID  Start_time  Finish_time  Exec_time
0         0      3    0.000000     5.714286   5.714286
1         1      4    0.000000     5.714286   5.714286
2         2      3    5.714286    11.428571   5.714286
3         3      0    5.714286    11.428571   5.714286
4         4      4    5.714286    11.428571   5.714286
..      ...    ...         ...          ...        ...
95       95      0  177.142857   182.857143   5.714286
96       96      3  182.857143   188.571429   5.714286
97       97      4  177.142857   182.857143   5.714286
98       98      4  182.857143   188.571429   5.714286
99       99      0  182.857143   188.571429   5.714286

[100 rows x 5 columns]
500
1371.4285714285713
500
     task_id  VM_ID   Start_time  Finish_time  Exec_time
0          0      2     0.000000     8.000000   8.000000
1          1      3     0.000000     5.714286   5.714286
2          2      3     5.714286    11.428571   5.714286
3          3      3    11.428571    17.142857   5.714286
4          4      4     0.000000     5.714286   5.714286
..       ...    ...          ...          ...        ...
495      495      3   462.857143   468.571429   5.714286
496      496      2   736.000000   744.000000   8.000000
497      497      4  1354.285714  1360.000000   5.714286
498      498      4  1360.000000  1365.714286   5.714286
499      499      4  1365.714286  1371.428571   5.714286

[500 rows x 5 columns]
1000
3456.0
1000
     task_id  VM_ID   Start_time  Finish_time  Exec_time
0          0      4     0.000000     5.714286   5.714286
1          1      4     5.714286    11.428571   5.714286
2          2      0     5.714286    11.428571   5.714286
3          3      0     5.714286    11.428571   5.714286
4          4      4    11.428571    17.142857   5.714286
..       ...    ...          ...          ...        ...
995      995      4  3200.000000  3205.714286   5.714286
996      996      4  3205.714286  3211.428571   5.714286
997      997      4  3211.428571  3217.142857   5.714286
998      998      3   685.714286   691.428571   5.714286
999      999      4  3217.142857  3222.857143   5.714286

[1000 rows x 5 columns]
1500
6560.0
1500
      task_id  VM_ID   Start_time  Finish_time  Exec_time
0           0      2     0.000000     8.000000   8.000000
1           1      0     0.000000     8.000000   8.000000
2           2      4     0.000000     5.714286   5.714286
3           3      1    16.000000    32.000000  16.000000
4           4      0    16.000000    32.000000  16.000000
...       ...    ...          ...          ...        ...
1495     1495      0  4085.714286  4091.428571   5.714286
1496     1496      4  4091.428571  4097.142857   5.714286
1497     1497      4  4097.142857  4102.857143   5.714286
1498     1498      0  4097.142857  4102.857143   5.714286
1499     1499      0  4097.142857  4102.857143   5.714286

[1500 rows x 5 columns]
2000
9600.0
2000
      task_id  VM_ID   Start_time  Finish_time  Exec_time
0           0      1     0.000000    16.000000  16.000000
1           1      4     0.000000     5.714286   5.714286
2           2      4     5.714286    11.428571   5.714286
3           3      3     0.000000     5.714286   5.714286
4           4      0     0.000000     5.714286   5.714286
...       ...    ...          ...          ...        ...
1995     1995      0  4891.428571  4897.142857   5.714286
1996     1996      0  4891.428571  4897.142857   5.714286
1997     1997      4  4897.142857  4902.857143   5.714286
1998     1998      0  4897.142857  4902.857143   5.714286
1999     1999      0  4897.142857  4902.857143   5.714286

[2000 rows x 5 columns]
2500
12272.0
2500
      task_id  VM_ID   Start_time  Finish_time  Exec_time
0           0      4     0.000000     5.714286   5.714286
1           1      3     0.000000     5.714286   5.714286
2           2      3     5.714286    11.428571   5.714286
3           3      4     5.714286    11.428571   5.714286
4           4      4    11.428571    17.142857   5.714286
...       ...    ...          ...          ...        ...
2495     2495      3  1605.714286  1611.428571   5.714286
2496     2496      2  2192.000000  2200.000000   8.000000
2497     2497      2  2200.000000  2208.000000   8.000000
2498     2498      2  2208.000000  2216.000000   8.000000
2499     2499      2  2216.000000  2224.000000   8.000000

[2500 rows x 5 columns]

<ipython-input-8-e9652d172dbe>:97: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2_exe.insert(1, f,exe1)
<ipython-input-8-e9652d172dbe>:98: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2_start.insert(1, f,average_start)
<ipython-input-8-e9652d172dbe>:99: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2_finish.insert(1, f,average_finish)
<ipython-input-8-e9652d172dbe>:100: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2_aexe.insert(1, f,average_exe)
<ipython-input-8-e9652d172dbe>:101: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2_util.insert(1, f,utili1)
<ipython-input-8-e9652d172dbe>:102: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2_power.insert(1, f,power)

100
188.57142857142858
100
    task_id  VM_ID  Start_time  Finish_time  Exec_time
0         0      4    0.000000     5.714286   5.714286
1         1      4    5.714286    11.428571   5.714286
2         2      3    0.000000     5.714286   5.714286
3         3      4   11.428571    17.142857   5.714286
4         4      3    5.714286    11.428571   5.714286
..      ...    ...         ...          ...        ...
95       95      3  171.428571   177.142857   5.714286
96       96      2  176.000000   184.000000   8.000000
97       97      4  182.857143   188.571429   5.714286
98       98      3  177.142857   182.857143   5.714286
99       99      3  182.857143   188.571429   5.714286

[100 rows x 5 columns]
500
937.1428571428539
500
     task_id  VM_ID  Start_time  Finish_time  Exec_time
0          0      4    0.000000     5.714286   5.714286
1          1      4    5.714286    11.428571   5.714286
2          2      2    0.000000     8.000000   8.000000
3          3      3    0.000000     5.714286   5.714286
4          4      1    0.000000    16.000000  16.000000
..       ...    ...         ...          ...        ...
495      495      3  914.285714   920.000000   5.714286
496      496      3  920.000000   925.714286   5.714286
497      497      3  925.714286   931.428571   5.714286
498      498      3  931.428571   937.142857   5.714286
499      499      1  912.000000   928.000000  16.000000

[500 rows x 5 columns]
1000
1862.8571428571483
1000
     task_id  VM_ID   Start_time  Finish_time  Exec_time
0          0      2     0.000000     8.000000   8.000000
1          1      4     0.000000     5.714286   5.714286
2          2      2     8.000000    16.000000   8.000000
3          3      1     0.000000    16.000000  16.000000
4          4      4     5.714286    11.428571   5.714286
..       ...    ...          ...          ...        ...
995      995      1  1824.000000  1840.000000  16.000000
996      996      1  1840.000000  1856.000000  16.000000
997      997      3  1851.428571  1857.142857   5.714286
998      998      4  1857.142857  1862.857143   5.714286
999      999      3  1857.142857  1862.857143   5.714286

[1000 rows x 5 columns]
1500
2800.0
1500
      task_id  VM_ID   Start_time  Finish_time  Exec_time
0           0      4     0.000000     5.714286   5.714286
1           1      2     0.000000     8.000000   8.000000
2           2      3     0.000000     5.714286   5.714286
3           3      4     5.714286    11.428571   5.714286
4           4      3     5.714286    11.428571   5.714286
...       ...    ...          ...          ...        ...
1495     1495      4  2777.142857  2782.857143   5.714286
1496     1496      3  2771.428571  2777.142857   5.714286
1497     1497      3  2777.142857  2782.857143   5.714286
1498     1498      2  2792.000000  2800.000000   8.000000
1499     1499      3  2782.857143  2788.571429   5.714286

[1500 rows x 5 columns]
2000
3725.714285714312
2000
      task_id  VM_ID   Start_time  Finish_time  Exec_time
0           0      1     0.000000    16.000000  16.000000
1           1      3     0.000000     5.714286   5.714286
2           2      0     0.000000     5.714286   5.714286
3           3      4     0.000000     5.714286   5.714286
4           4      2     0.000000     8.000000   8.000000
...       ...    ...          ...          ...        ...
1995     1995      3  3708.571429  3714.285714   5.714286
1996     1996      3  3714.285714  3720.000000   5.714286
1997     1997      2  3696.000000  3704.000000   8.000000
1998     1998      2  3704.000000  3712.000000   8.000000
1999     1999      3  3720.000000  3725.714286   5.714286

[2000 rows x 5 columns]
2500
4662.857142857135
2500
      task_id  VM_ID   Start_time  Finish_time  Exec_time
0           0      4     0.000000     5.714286   5.714286
1           1      3     0.000000     5.714286   5.714286
2           2      2     0.000000     8.000000   8.000000
3           3      3     5.714286    11.428571   5.714286
4           4      2     8.000000    16.000000   8.000000
...       ...    ...          ...          ...        ...
2495     2495      4  4651.428571  4657.142857   5.714286
2496     2496      3  4645.714286  4651.428571   5.714286
2497     2497      3  4651.428571  4657.142857   5.714286
2498     2498      2  4616.000000  4624.000000   8.000000
2499     2499      4  4657.142857  4662.857143   5.714286

[2500 rows x 5 columns]

<ipython-input-8-e9652d172dbe>:97: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2_exe.insert(1, f,exe1)
<ipython-input-8-e9652d172dbe>:98: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2_start.insert(1, f,average_start)
<ipython-input-8-e9652d172dbe>:99: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2_finish.insert(1, f,average_finish)
<ipython-input-8-e9652d172dbe>:100: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2_aexe.insert(1, f,average_exe)
<ipython-input-8-e9652d172dbe>:101: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2_util.insert(1, f,utili1)
<ipython-input-8-e9652d172dbe>:102: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2_power.insert(1, f,power)

100
188.57142857142858
100
    task_id  VM_ID  Start_time  Finish_time  Exec_time
0         0      1    0.000000    16.000000  16.000000
1         1      2    0.000000     8.000000   8.000000
2         2      3    0.000000     5.714286   5.714286
3         3      4    0.000000     5.714286   5.714286
4         4      0    0.000000     5.714286   5.714286
..      ...    ...         ...          ...        ...
95       95      4  177.142857   182.857143   5.714286
96       96      3  182.857143   188.571429   5.714286
97       97      1  160.000000   176.000000  16.000000
98       98      2  176.000000   184.000000   8.000000
99       99      4  182.857143   188.571429   5.714286

[100 rows x 5 columns]
500
1088.0
500
     task_id  VM_ID   Start_time  Finish_time  Exec_time
0          0      4     0.000000     5.714286   5.714286
1          1      4     5.714286    11.428571   5.714286
2          2      3     0.000000     5.714286   5.714286
3          3      4    11.428571    17.142857   5.714286
4          4      3     5.714286    11.428571   5.714286
..       ...    ...          ...          ...        ...
495      495      4   594.285714   600.000000   5.714286
496      496      3  1074.285714  1080.000000   5.714286
497      497      1  1072.000000  1088.000000  16.000000
498      498      3  1080.000000  1085.714286   5.714286
499      499      4   600.000000   605.714286   5.714286

[500 rows x 5 columns]
1000
2848.0
1000
     task_id  VM_ID   Start_time  Finish_time  Exec_time
0          0      3     0.000000     5.714286   5.714286
1          1      4     0.000000     5.714286   5.714286
2          2      2     0.000000     8.000000   8.000000
3          3      2     8.000000    16.000000   8.000000
4          4      3     5.714286    11.428571   5.714286
..       ...    ...          ...          ...        ...
995      995      2  2840.000000  2848.000000   8.000000
996      996      4   920.000000   925.714286   5.714286
997      997      4   925.714286   931.428571   5.714286
998      998      3  1731.428571  1737.142857   5.714286
999      999      1  2816.000000  2832.000000  16.000000

[1000 rows x 5 columns]
1500
5584.0
1500
      task_id  VM_ID   Start_time  Finish_time  Exec_time
0           0      1     0.000000    16.000000  16.000000
1           1      2     0.000000     8.000000   8.000000
2           2      3     0.000000     5.714286   5.714286
3           3      1    16.000000    32.000000  16.000000
4           4      2     8.000000    16.000000   8.000000
...       ...    ...          ...          ...        ...
1495     1495      2  4048.000000  4056.000000   8.000000
1496     1496      3  2274.285714  2280.000000   5.714286
1497     1497      2  4056.000000  4064.000000   8.000000
1498     1498      3  2280.000000  2285.714286   5.714286
1499     1499      1  5568.000000  5584.000000  16.000000

[1500 rows x 5 columns]
2000
8064.0
2000
      task_id  VM_ID  Start_time  Finish_time  Exec_time
0           0      2         0.0     8.000000   8.000000
1           1      1         0.0    16.000000  16.000000
2           2      1        16.0    32.000000  16.000000
3           3      3         0.0     5.714286   5.714286
4           4      2         8.0    16.000000   8.000000
...       ...    ...         ...          ...        ...
1995     1995      1      8016.0  8032.000000  16.000000
1996     1996      2      4608.0  4616.000000   8.000000
1997     1997      2      4616.0  4624.000000   8.000000
1998     1998      1      8032.0  8048.000000  16.000000
1999     1999      1      8048.0  8064.000000  16.000000

[2000 rows x 5 columns]
2500
10944.0
2500
      task_id  VM_ID    Start_time   Finish_time  Exec_time
0           0      2      0.000000      8.000000   8.000000
1           1      4      0.000000      5.714286   5.714286
2           2      2      8.000000     16.000000   8.000000
3           3      3      0.000000      5.714286   5.714286
4           4      0      0.000000      5.714286   5.714286
...       ...    ...           ...           ...        ...
2495     2495      1  10896.000000  10912.000000  16.000000
2496     2496      2   5688.000000   5696.000000   8.000000
2497     2497      1  10912.000000  10928.000000  16.000000
2498     2498      1  10928.000000  10944.000000  16.000000
2499     2499      3   4411.428571   4417.142857   5.714286

[2500 rows x 5 columns]
100

<ipython-input-8-e9652d172dbe>:97: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2_exe.insert(1, f,exe1)
<ipython-input-8-e9652d172dbe>:98: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2_start.insert(1, f,average_start)
<ipython-input-8-e9652d172dbe>:99: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2_finish.insert(1, f,average_finish)
<ipython-input-8-e9652d172dbe>:100: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2_aexe.insert(1, f,average_exe)
<ipython-input-8-e9652d172dbe>:101: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2_util.insert(1, f,utili1)
<ipython-input-8-e9652d172dbe>:102: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2_power.insert(1, f,power)

352.0
100
    task_id  VM_ID  Start_time  Finish_time  Exec_time
0         0      2    0.000000     8.000000   8.000000
1         1      2    8.000000    16.000000   8.000000
2         2      3    0.000000     5.714286   5.714286
3         3      2   16.000000    24.000000   8.000000
4         4      4    0.000000     5.714286   5.714286
..      ...    ...         ...          ...        ...
95       95      1  320.000000   336.000000  16.000000
96       96      2  216.000000   224.000000   8.000000
97       97      1  336.000000   352.000000  16.000000
98       98      2  224.000000   232.000000   8.000000
99       99      3  211.428571   217.142857   5.714286

[100 rows x 5 columns]
500
2491.428571428584
500
     task_id  VM_ID   Start_time  Finish_time  Exec_time
0          0      4     0.000000     5.714286   5.714286
1          1      4     5.714286    11.428571   5.714286
2          2      4    11.428571    17.142857   5.714286
3          3      4    17.142857    22.857143   5.714286
4          4      4    22.857143    28.571429   5.714286
..       ...    ...          ...          ...        ...
495      495      4  2462.857143  2468.571429   5.714286
496      496      4  2468.571429  2474.285714   5.714286
497      497      4  2474.285714  2480.000000   5.714286
498      498      4  2480.000000  2485.714286   5.714286
499      499      4  2485.714286  2491.428571   5.714286

[500 rows x 5 columns]
1000
5296.0
1000
     task_id  VM_ID   Start_time  Finish_time  Exec_time
0          0      4     0.000000     5.714286   5.714286
1          1      3     0.000000     5.714286   5.714286
2          2      3     5.714286    11.428571   5.714286
3          3      4     5.714286    11.428571   5.714286
4          4      0     5.714286    11.428571   5.714286
..       ...    ...          ...          ...        ...
995      995      2  2080.000000  2088.000000   8.000000
996      996      1  5264.000000  5280.000000  16.000000
997      997      1  5280.000000  5296.000000  16.000000
998      998      2  2088.000000  2096.000000   8.000000
999      999      4   771.428571   777.142857   5.714286

[1000 rows x 5 columns]
1500
An exception occurred local variable 'start' referenced before assignment
2000
11152.0
2000
      task_id  VM_ID    Start_time   Finish_time  Exec_time
0           0      2      0.000000      8.000000   8.000000
1           1      4      0.000000      5.714286   5.714286
2           2      1      0.000000     16.000000  16.000000
3           3      2      8.000000     16.000000   8.000000
4           4      4      5.714286     11.428571   5.714286
...       ...    ...           ...           ...        ...
1995     1995      1  11104.000000  11120.000000  16.000000
1996     1996      4   1440.000000   1445.714286   5.714286
1997     1997      1  11120.000000  11136.000000  16.000000
1998     1998      3   3017.142857   3022.857143   5.714286
1999     1999      1  11136.000000  11152.000000  16.000000

[2000 rows x 5 columns]
2500
13872.0
2500
      task_id  VM_ID    Start_time   Finish_time  Exec_time
0           0      2      0.000000      8.000000   8.000000
1           1      1      0.000000     16.000000  16.000000
2           2      2      8.000000     16.000000   8.000000
3           3      3      0.000000      5.714286   5.714286
4           4      1     16.000000     32.000000  16.000000
...       ...    ...           ...           ...        ...
2495     2495      0  13792.000000  13808.000000  16.000000
2496     2496      1  13840.000000  13856.000000  16.000000
2497     2497      3   3765.714286   3771.428571   5.714286
2498     2498      4   1880.000000   1885.714286   5.714286
2499     2499      0   1880.000000   1885.714286   5.714286

[2500 rows x 5 columns]
algo not found
100
188.57142857142858
100
    task_id  VM_ID  Start_time  Finish_time  Exec_time
0         0      4    0.000000     5.714286   5.714286
1         1      4    5.714286    11.428571   5.714286
2         2      1    0.000000    16.000000  16.000000
3         3      2    0.000000     8.000000   8.000000
4         4      2    8.000000    16.000000   8.000000
..      ...    ...         ...          ...        ...
95       95      4  182.857143   188.571429   5.714286
96       96      1  160.000000   176.000000  16.000000
97       97      2  168.000000   176.000000   8.000000
98       98      2  176.000000   184.000000   8.000000
99       99      3  182.857143   188.571429   5.714286

[100 rows x 5 columns]
500
931.4285714285683
500
     task_id  VM_ID  Start_time  Finish_time  Exec_time
0          0      4    0.000000     5.714286   5.714286
1          1      4    5.714286    11.428571   5.714286
2          2      4   11.428571    17.142857   5.714286
3          3      3    0.000000     5.714286   5.714286
4          4      4   17.142857    22.857143   5.714286
..       ...    ...         ...          ...        ...
495      495      2  904.000000   912.000000   8.000000
496      496      0  904.000000   912.000000   8.000000
497      497      2  912.000000   920.000000   8.000000
498      498      3  925.714286   931.428571   5.714286
499      499      2  920.000000   928.000000   8.000000

[500 rows x 5 columns]
1000
1862.8571428571483
1000
     task_id  VM_ID   Start_time  Finish_time  Exec_time
0          0      1     0.000000    16.000000  16.000000
1          1      4     0.000000     5.714286   5.714286
2          2      3     0.000000     5.714286   5.714286
3          3      2     0.000000     8.000000   8.000000
4          4      3     5.714286    11.428571   5.714286
..       ...    ...          ...          ...        ...
995      995      2  1848.000000  1856.000000   8.000000
996      996      3  1851.428571  1857.142857   5.714286
997      997      3  1857.142857  1862.857143   5.714286
998      998      4  1851.428571  1857.142857   5.714286
999      999      4  1857.142857  1862.857143   5.714286

[1000 rows x 5 columns]
1500
2794.28571428573
1500
      task_id  VM_ID   Start_time  Finish_time  Exec_time
0           0      2     0.000000     8.000000   8.000000
1           1      2     8.000000    16.000000   8.000000
2           2      3     0.000000     5.714286   5.714286
3           3      3     5.714286    11.428571   5.714286
4           4      4     0.000000     5.714286   5.714286
...       ...    ...          ...          ...        ...
1495     1495      1  2768.000000  2784.000000  16.000000
1496     1496      4  2782.857143  2788.571429   5.714286
1497     1497      2  2784.000000  2792.000000   8.000000
1498     1498      3  2782.857143  2788.571429   5.714286
1499     1499      3  2788.571429  2794.285714   5.714286

[1500 rows x 5 columns]
2000
3725.714285714312
2000
      task_id  VM_ID   Start_time  Finish_time  Exec_time
0           0      4     0.000000     5.714286   5.714286
1           1      4     5.714286    11.428571   5.714286
2           2      1     0.000000    16.000000  16.000000
3           3      3     0.000000     5.714286   5.714286
4           4      2     0.000000     8.000000   8.000000
...       ...    ...          ...          ...        ...
1995     1995      2  3712.000000  3720.000000   8.000000
1996     1996      1  3648.000000  3664.000000  16.000000
1997     1997      3  3720.000000  3725.714286   5.714286
1998     1998      0  3720.000000  3725.714286   5.714286
1999     1999      1  3680.000000  3696.000000  16.000000

[2000 rows x 5 columns]
2500
4656.0
2500
      task_id  VM_ID   Start_time  Finish_time  Exec_time
0           0      1     0.000000    16.000000  16.000000
1           1      4     0.000000     5.714286   5.714286
2           2      2     0.000000     8.000000   8.000000
3           3      4     5.714286    11.428571   5.714286
4           4      4    11.428571    17.142857   5.714286
...       ...    ...          ...          ...        ...
2495     2495      2  4648.000000  4656.000000   8.000000
2496     2496      3  4645.714286  4651.428571   5.714286
2497     2497      4  4634.285714  4640.000000   5.714286
2498     2498      4  4640.000000  4645.714286   5.714286
2499     2499      4  4645.714286  4651.428571   5.714286

[2500 rows x 5 columns]

<ipython-input-8-e9652d172dbe>:97: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2_exe.insert(1, f,exe1)
<ipython-input-8-e9652d172dbe>:98: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2_start.insert(1, f,average_start)
<ipython-input-8-e9652d172dbe>:99: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2_finish.insert(1, f,average_finish)
<ipython-input-8-e9652d172dbe>:100: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2_aexe.insert(1, f,average_exe)
<ipython-input-8-e9652d172dbe>:101: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2_util.insert(1, f,utili1)
<ipython-input-8-e9652d172dbe>:102: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2_power.insert(1, f,power)

100
272.0
100
    task_id  VM_ID  Start_time  Finish_time  Exec_time
0         0      3    0.000000     5.714286   5.714286
1         1      1    0.000000    16.000000  16.000000
2         2      3    5.714286    11.428571   5.714286
3         3      0    5.714286    11.428571   5.714286
4         4      3   11.428571    17.142857   5.714286
..      ...    ...         ...          ...        ...
95       95      4   22.857143    28.571429   5.714286
96       96      2  256.000000   264.000000   8.000000
97       97      3  240.000000   245.714286   5.714286
98       98      2  264.000000   272.000000   8.000000
99       99      3  245.714286   251.428571   5.714286

[100 rows x 5 columns]
500
1552.0
500
     task_id  VM_ID   Start_time  Finish_time  Exec_time
0          0      2     0.000000     8.000000   8.000000
1          1      3     0.000000     5.714286   5.714286
2          2      1     0.000000    16.000000  16.000000
3          3      1    16.000000    32.000000  16.000000
4          4      3     5.714286    11.428571   5.714286
..       ...    ...          ...          ...        ...
495      495      3  1028.571429  1034.285714   5.714286
496      496      1  1536.000000  1552.000000  16.000000
497      497      3  1034.285714  1040.000000   5.714286
498      498      3  1040.000000  1045.714286   5.714286
499      499      2  1544.000000  1552.000000   8.000000

[500 rows x 5 columns]
1000
3136.0
1000
     task_id  VM_ID   Start_time  Finish_time  Exec_time
0          0      3     0.000000     5.714286   5.714286
1          1      3     5.714286    11.428571   5.714286
2          2      2     0.000000     8.000000   8.000000
3          3      3    11.428571    17.142857   5.714286
4          4      3    17.142857    22.857143   5.714286
..       ...    ...          ...          ...        ...
995      995      3  2022.857143  2028.571429   5.714286
996      996      0  2022.857143  2028.571429   5.714286
997      997      2  3128.000000  3136.000000   8.000000
998      998      3  2028.571429  2034.285714   5.714286
999      999      1  3104.000000  3120.000000  16.000000

[1000 rows x 5 columns]
1500
5160.0
1500
      task_id  VM_ID   Start_time  Finish_time  Exec_time
0           0      2     0.000000     8.000000   8.000000
1           1      2     8.000000    16.000000   8.000000
2           2      2    16.000000    24.000000   8.000000
3           3      2    24.000000    32.000000   8.000000
4           4      3     0.000000     5.714286   5.714286
...       ...    ...          ...          ...        ...
1495     1495      1  5120.000000  5136.000000  16.000000
1496     1496      2  5152.000000  5160.000000   8.000000
1497     1497      3  2548.571429  2554.285714   5.714286
1498     1498      3  2554.285714  2560.000000   5.714286
1499     1499      1  5136.000000  5152.000000  16.000000

[1500 rows x 5 columns]
2000
6928.0
2000
      task_id  VM_ID   Start_time  Finish_time  Exec_time
0           0      2     0.000000     8.000000   8.000000
1           1      0     0.000000     8.000000   8.000000
2           2      0     0.000000     8.000000   8.000000
3           3      3     0.000000     5.714286   5.714286
4           4      3     5.714286    11.428571   5.714286
...       ...    ...          ...          ...        ...
1995     1995      2  6912.000000  6920.000000   8.000000
1996     1996      3  3434.285714  3440.000000   5.714286
1997     1997      3  3440.000000  3445.714286   5.714286
1998     1998      3  3445.714286  3451.428571   5.714286
1999     1999      2  6920.000000  6928.000000   8.000000

[2000 rows x 5 columns]
2500
8632.0
2500
      task_id  VM_ID   Start_time  Finish_time  Exec_time
0           0      2     0.000000     8.000000   8.000000
1           1      2     8.000000    16.000000   8.000000
2           2      3     0.000000     5.714286   5.714286
3           3      3     5.714286    11.428571   5.714286
4           4      2    16.000000    24.000000   8.000000
...       ...    ...          ...          ...        ...
2495     2495      3  4262.857143  4268.571429   5.714286
2496     2496      3  4268.571429  4274.285714   5.714286
2497     2497      2  8624.000000  8632.000000   8.000000
2498     2498      3  4274.285714  4280.000000   5.714286
2499     2499      1  8608.000000  8624.000000  16.000000

[2500 rows x 5 columns]

<ipython-input-8-e9652d172dbe>:97: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2_exe.insert(1, f,exe1)
<ipython-input-8-e9652d172dbe>:98: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2_start.insert(1, f,average_start)
<ipython-input-8-e9652d172dbe>:99: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2_finish.insert(1, f,average_finish)
<ipython-input-8-e9652d172dbe>:100: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2_aexe.insert(1, f,average_exe)
<ipython-input-8-e9652d172dbe>:101: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2_util.insert(1, f,utili1)
<ipython-input-8-e9652d172dbe>:102: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2_power.insert(1, f,power)

100
432.0
100
    task_id  VM_ID  Start_time  Finish_time  Exec_time
0         0      3    0.000000     5.714286   5.714286
1         1      4    0.000000     5.714286   5.714286
2         2      4    5.714286    11.428571   5.714286
3         3      0    5.714286    11.428571   5.714286
4         4      3    5.714286    11.428571   5.714286
..      ...    ...         ...          ...        ...
95       95      4   68.571429    74.285714   5.714286
96       96      3  154.285714   160.000000   5.714286
97       97      2  232.000000   240.000000   8.000000
98       98      2  240.000000   248.000000   8.000000
99       99      4   74.285714    80.000000   5.714286

[100 rows x 5 columns]
500
2496.0
500
     task_id  VM_ID   Start_time  Finish_time  Exec_time
0          0      3     0.000000     5.714286   5.714286
1          1      3     5.714286    11.428571   5.714286
2          2      1     0.000000    16.000000  16.000000
3          3      2     0.000000     8.000000   8.000000
4          4      4     0.000000     5.714286   5.714286
..       ...    ...          ...          ...        ...
495      495      2  1192.000000  1200.000000   8.000000
496      496      2  1200.000000  1208.000000   8.000000
497      497      0  1200.000000  1208.000000   8.000000
498      498      4   382.857143   388.571429   5.714286
499      499      1  2480.000000  2496.000000  16.000000

[500 rows x 5 columns]
1000
5488.0
1000
     task_id  VM_ID   Start_time  Finish_time  Exec_time
0          0      2     0.000000     8.000000   8.000000
1          1      3     0.000000     5.714286   5.714286
2          2      1     0.000000    16.000000  16.000000
3          3      1    16.000000    32.000000  16.000000
4          4      0    16.000000    32.000000  16.000000
..       ...    ...          ...          ...        ...
995      995      3  1571.428571  1577.142857   5.714286
996      996      1  5456.000000  5472.000000  16.000000
997      997      1  5472.000000  5488.000000  16.000000
998      998      2  2032.000000  2040.000000   8.000000
999      999      4   714.285714   720.000000   5.714286

[1000 rows x 5 columns]
1500
8528.0
1500
      task_id  VM_ID   Start_time  Finish_time  Exec_time
0           0      3     0.000000     5.714286   5.714286
1           1      2     0.000000     8.000000   8.000000
2           2      2     8.000000    16.000000   8.000000
3           3      2    16.000000    24.000000   8.000000
4           4      3     5.714286    11.428571   5.714286
...       ...    ...          ...          ...        ...
1495     1495      3  2125.714286  2131.428571   5.714286
1496     1496      2  3216.000000  3224.000000   8.000000
1497     1497      0  3216.000000  3224.000000   8.000000
1498     1498      2  3224.000000  3232.000000   8.000000
1499     1499      1  8512.000000  8528.000000  16.000000

[1500 rows x 5 columns]
2000
10912.0
2000
      task_id  VM_ID    Start_time   Finish_time  Exec_time
0           0      1      0.000000     16.000000  16.000000
1           1      3      0.000000      5.714286   5.714286
2           2      3      5.714286     11.428571   5.714286
3           3      2      0.000000      8.000000   8.000000
4           4      1     16.000000     32.000000  16.000000
...       ...    ...           ...           ...        ...
1995     1995      3   2960.000000   2965.714286   5.714286
1996     1996      4   1474.285714   1480.000000   5.714286
1997     1997      3   2965.714286   2971.428571   5.714286
1998     1998      1  10896.000000  10912.000000  16.000000
1999     1999      3   2971.428571   2977.142857   5.714286

[2000 rows x 5 columns]
2500
14192.0
2500
      task_id  VM_ID    Start_time   Finish_time  Exec_time
0           0      1      0.000000     16.000000  16.000000
1           1      1     16.000000     32.000000  16.000000
2           2      2      0.000000      8.000000   8.000000
3           3      2      8.000000     16.000000   8.000000
4           4      4      0.000000      5.714286   5.714286
...       ...    ...           ...           ...        ...
2495     2495      1  14160.000000  14176.000000  16.000000
2496     2496      1  14176.000000  14192.000000  16.000000
2497     2497      3   3725.714286   3731.428571   5.714286
2498     2498      3   3731.428571   3737.142857   5.714286
2499     2499      3   3737.142857   3742.857143   5.714286

[2500 rows x 5 columns]

<ipython-input-8-e9652d172dbe>:97: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2_exe.insert(1, f,exe1)
<ipython-input-8-e9652d172dbe>:98: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2_start.insert(1, f,average_start)
<ipython-input-8-e9652d172dbe>:99: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2_finish.insert(1, f,average_finish)
<ipython-input-8-e9652d172dbe>:100: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2_aexe.insert(1, f,average_exe)
<ipython-input-8-e9652d172dbe>:101: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2_util.insert(1, f,utili1)
<ipython-input-8-e9652d172dbe>:102: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2_power.insert(1, f,power)

100
192.0
100
    task_id  VM_ID  Start_time  Finish_time  Exec_time
0         0      4    0.000000     5.714286   5.714286
1         1      1    0.000000    16.000000  16.000000
2         2      3    0.000000     5.714286   5.714286
3         3      3    5.714286    11.428571   5.714286
4         4      2    0.000000     8.000000   8.000000
..      ...    ...         ...          ...        ...
95       95      3  177.142857   182.857143   5.714286
96       96      3  182.857143   188.571429   5.714286
97       97      2  176.000000   184.000000   8.000000
98       98      1  160.000000   176.000000  16.000000
99       99      2  184.000000   192.000000   8.000000

[100 rows x 5 columns]
500
971.4285714285679
500
     task_id  VM_ID  Start_time  Finish_time  Exec_time
0          0      3    0.000000     5.714286   5.714286
1          1      3    5.714286    11.428571   5.714286
2          2      2    0.000000     8.000000   8.000000
3          3      4    0.000000     5.714286   5.714286
4          4      2    8.000000    16.000000   8.000000
..       ...    ...         ...          ...        ...
495      495      1  896.000000   912.000000  16.000000
496      496      3  960.000000   965.714286   5.714286
497      497      3  965.714286   971.428571   5.714286
498      498      4  914.285714   920.000000   5.714286
499      499      4  920.000000   925.714286   5.714286

[500 rows x 5 columns]
1000
1912.0
1000
     task_id  VM_ID   Start_time  Finish_time  Exec_time
0          0      4     0.000000     5.714286   5.714286
1          1      4     5.714286    11.428571   5.714286
2          2      3     0.000000     5.714286   5.714286
3          3      2     0.000000     8.000000   8.000000
4          4      3     5.714286    11.428571   5.714286
..       ...    ...          ...          ...        ...
995      995      4  1748.571429  1754.285714   5.714286
996      996      1  1888.000000  1904.000000  16.000000
997      997      2  1904.000000  1912.000000   8.000000
998      998      3  1902.857143  1908.571429   5.714286
999      999      4  1754.285714  1760.000000   5.714286

[1000 rows x 5 columns]
1500
2891.4285714285884
1500
      task_id  VM_ID   Start_time  Finish_time  Exec_time
0           0      3     0.000000     5.714286   5.714286
1           1      3     5.714286    11.428571   5.714286
2           2      4     0.000000     5.714286   5.714286
3           3      0     0.000000     5.714286   5.714286
4           4      1    16.000000    32.000000  16.000000
...       ...    ...          ...          ...        ...
1495     1495      3  2880.000000  2885.714286   5.714286
1496     1496      3  2885.714286  2891.428571   5.714286
1497     1497      4  2857.142857  2862.857143   5.714286
1498     1498      4  2862.857143  2868.571429   5.714286
1499     1499      2  2664.000000  2672.000000   8.000000

[1500 rows x 5 columns]
2000
3840.0000000000277
2000
      task_id  VM_ID   Start_time  Finish_time  Exec_time
0           0      2     0.000000     8.000000   8.000000
1           1      1     0.000000    16.000000  16.000000
2           2      3     0.000000     5.714286   5.714286
3           3      3     5.714286    11.428571   5.714286
4           4      2     8.000000    16.000000   8.000000
...       ...    ...          ...          ...        ...
1995     1995      4  3628.571429  3634.285714   5.714286
1996     1996      4  3634.285714  3640.000000   5.714286
1997     1997      2  3736.000000  3744.000000   8.000000
1998     1998      4  3640.000000  3645.714286   5.714286
1999     1999      3  3834.285714  3840.000000   5.714286

[2000 rows x 5 columns]
2500
4954.2857142856865
2500
      task_id  VM_ID   Start_time  Finish_time  Exec_time
0           0      3     0.000000     5.714286   5.714286
1           1      2     0.000000     8.000000   8.000000
2           2      3     5.714286    11.428571   5.714286
3           3      3    11.428571    17.142857   5.714286
4           4      4     0.000000     5.714286   5.714286
...       ...    ...          ...          ...        ...
2495     2495      0  4942.857143  4948.571429   5.714286
2496     2496      4  4948.571429  4954.285714   5.714286
2497     2497      2  4144.000000  4152.000000   8.000000
2498     2498      2  4152.000000  4160.000000   8.000000
2499     2499      3  4948.571429  4954.285714   5.714286

[2500 rows x 5 columns]

<ipython-input-8-e9652d172dbe>:97: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2_exe.insert(1, f,exe1)
<ipython-input-8-e9652d172dbe>:98: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2_start.insert(1, f,average_start)
<ipython-input-8-e9652d172dbe>:99: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2_finish.insert(1, f,average_finish)
<ipython-input-8-e9652d172dbe>:100: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2_aexe.insert(1, f,average_exe)
<ipython-input-8-e9652d172dbe>:101: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2_util.insert(1, f,utili1)
<ipython-input-8-e9652d172dbe>:102: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2_power.insert(1, f,power)

100
192.0
100
    task_id  VM_ID  Start_time  Finish_time  Exec_time
0         0      3    0.000000     5.714286   5.714286
1         1      4    0.000000     5.714286   5.714286
2         2      0    0.000000     5.714286   5.714286
3         3      3    5.714286    11.428571   5.714286
4         4      3   11.428571    17.142857   5.714286
..      ...    ...         ...          ...        ...
95       95      3  177.142857   182.857143   5.714286
96       96      4  171.428571   177.142857   5.714286
97       97      4  177.142857   182.857143   5.714286
98       98      1  160.000000   176.000000  16.000000
99       99      3  182.857143   188.571429   5.714286

[100 rows x 5 columns]
500
944.0
500
     task_id  VM_ID  Start_time  Finish_time  Exec_time
0          0      3    0.000000     5.714286   5.714286
1          1      3    5.714286    11.428571   5.714286
2          2      4    0.000000     5.714286   5.714286
3          3      2    0.000000     8.000000   8.000000
4          4      2    8.000000    16.000000   8.000000
..       ...    ...         ...          ...        ...
495      495      3  897.142857   902.857143   5.714286
496      496      0  897.142857   902.857143   5.714286
497      497      3  902.857143   908.571429   5.714286
498      498      4  931.428571   937.142857   5.714286
499      499      3  908.571429   914.285714   5.714286

[500 rows x 5 columns]
1000
1897.142857142863
1000
     task_id  VM_ID   Start_time  Finish_time  Exec_time
0          0      2     0.000000     8.000000   8.000000
1          1      2     8.000000    16.000000   8.000000
2          2      4     0.000000     5.714286   5.714286
3          3      2    16.000000    24.000000   8.000000
4          4      0    16.000000    24.000000   8.000000
..       ...    ...          ...          ...        ...
995      995      3  1885.714286  1891.428571   5.714286
996      996      2  1848.000000  1856.000000   8.000000
997      997      3  1891.428571  1897.142857   5.714286
998      998      4  1822.857143  1828.571429   5.714286
999      999      4  1828.571429  1834.285714   5.714286

[1000 rows x 5 columns]
1500
2840.0
1500
      task_id  VM_ID   Start_time  Finish_time  Exec_time
0           0      3     0.000000     5.714286   5.714286
1           1      2     0.000000     8.000000   8.000000
2           2      4     0.000000     5.714286   5.714286
3           3      4     5.714286    11.428571   5.714286
4           4      4    11.428571    17.142857   5.714286
...       ...    ...          ...          ...        ...
1495     1495      3  2737.142857  2742.857143   5.714286
1496     1496      2  2824.000000  2832.000000   8.000000
1497     1497      4  2822.857143  2828.571429   5.714286
1498     1498      4  2828.571429  2834.285714   5.714286
1499     1499      2  2832.000000  2840.000000   8.000000

[1500 rows x 5 columns]
2000
3748.5714285714553
2000
      task_id  VM_ID   Start_time  Finish_time  Exec_time
0           0      3     0.000000     5.714286   5.714286
1           1      1     0.000000    16.000000  16.000000
2           2      4     0.000000     5.714286   5.714286
3           3      1    16.000000    32.000000  16.000000
4           4      1    32.000000    48.000000  16.000000
...       ...    ...          ...          ...        ...
1995     1995      4  3708.571429  3714.285714   5.714286
1996     1996      4  3714.285714  3720.000000   5.714286
1997     1997      2  3712.000000  3720.000000   8.000000
1998     1998      3  3737.142857  3742.857143   5.714286
1999     1999      3  3742.857143  3748.571429   5.714286

[2000 rows x 5 columns]
2500
4737.142857142844
2500
      task_id  VM_ID   Start_time  Finish_time  Exec_time
0           0      3     0.000000     5.714286   5.714286
1           1      3     5.714286    11.428571   5.714286
2           2      3    11.428571    17.142857   5.714286
3           3      2     0.000000     8.000000   8.000000
4           4      4     0.000000     5.714286   5.714286
...       ...    ...          ...          ...        ...
2495     2495      3  4491.428571  4497.142857   5.714286
2496     2496      3  4497.142857  4502.857143   5.714286
2497     2497      4  4731.428571  4737.142857   5.714286
2498     2498      3  4502.857143  4508.571429   5.714286
2499     2499      3  4508.571429  4514.285714   5.714286

[2500 rows x 5 columns]
100

<ipython-input-8-e9652d172dbe>:97: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2_exe.insert(1, f,exe1)
<ipython-input-8-e9652d172dbe>:98: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2_start.insert(1, f,average_start)
<ipython-input-8-e9652d172dbe>:99: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2_finish.insert(1, f,average_finish)
<ipython-input-8-e9652d172dbe>:100: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2_aexe.insert(1, f,average_exe)
<ipython-input-8-e9652d172dbe>:101: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2_util.insert(1, f,utili1)
<ipython-input-8-e9652d172dbe>:102: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2_power.insert(1, f,power)

320.00000000000017
100
    task_id  VM_ID  Start_time  Finish_time  Exec_time
0         0      4    0.000000     5.714286   5.714286
1         1      3    0.000000     5.714286   5.714286
2         2      4    5.714286    11.428571   5.714286
3         3      4   11.428571    17.142857   5.714286
4         4      3    5.714286    11.428571   5.714286
..      ...    ...         ...          ...        ...
95       95      4  297.142857   302.857143   5.714286
96       96      3  137.142857   142.857143   5.714286
97       97      4  302.857143   308.571429   5.714286
98       98      4  308.571429   314.285714   5.714286
99       99      4  314.285714   320.000000   5.714286

[100 rows x 5 columns]
500
1697.1428571428607
500
     task_id  VM_ID   Start_time  Finish_time  Exec_time
0          0      4     0.000000     5.714286   5.714286
1          1      1     0.000000    16.000000  16.000000
2          2      4     5.714286    11.428571   5.714286
3          3      4    11.428571    17.142857   5.714286
4          4      4    17.142857    22.857143   5.714286
..       ...    ...          ...          ...        ...
495      495      2   480.000000   488.000000   8.000000
496      496      4  1685.714286  1691.428571   5.714286
497      497      1   560.000000   576.000000  16.000000
498      498      4  1691.428571  1697.142857   5.714286
499      499      3   600.000000   605.714286   5.714286

[500 rows x 5 columns]
1000
3371.428571428594
1000
     task_id  VM_ID   Start_time  Finish_time  Exec_time
0          0      4     0.000000     5.714286   5.714286
1          1      2     0.000000     8.000000   8.000000
2          2      4     5.714286    11.428571   5.714286
3          3      4    11.428571    17.142857   5.714286
4          4      3     0.000000     5.714286   5.714286
..       ...    ...          ...          ...        ...
995      995      2  1104.000000  1112.000000   8.000000
996      996      4  3348.571429  3354.285714   5.714286
997      997      4  3354.285714  3360.000000   5.714286
998      998      4  3360.000000  3365.714286   5.714286
999      999      4  3365.714286  3371.428571   5.714286

[1000 rows x 5 columns]
1500
5177.142857142814
1500
      task_id  VM_ID   Start_time  Finish_time  Exec_time
0           0      2     0.000000     8.000000   8.000000
1           1      4     0.000000     5.714286   5.714286
2           2      4     5.714286    11.428571   5.714286
3           3      2     8.000000    16.000000   8.000000
4           4      4    11.428571    17.142857   5.714286
...       ...    ...          ...          ...        ...
1495     1495      4  5160.000000  5165.714286   5.714286
1496     1496      1  1504.000000  1520.000000  16.000000
1497     1497      4  5165.714286  5171.428571   5.714286
1498     1498      3  1674.285714  1680.000000   5.714286
1499     1499      4  5171.428571  5177.142857   5.714286

[1500 rows x 5 columns]
2000
6839.999999999844
2000
      task_id  VM_ID   Start_time  Finish_time  Exec_time
0           0      1     0.000000    16.000000  16.000000
1           1      4     0.000000     5.714286   5.714286
2           2      4     5.714286    11.428571   5.714286
3           3      3     0.000000     5.714286   5.714286
4           4      4    11.428571    17.142857   5.714286
...       ...    ...          ...          ...        ...
1995     1995      4  6822.857143  6828.571429   5.714286
1996     1996      4  6828.571429  6834.285714   5.714286
1997     1997      3  2325.714286  2331.428571   5.714286
1998     1998      3  2331.428571  2337.142857   5.714286
1999     1999      4  6834.285714  6840.000000   5.714286

[2000 rows x 5 columns]
2500
8514.285714285495
2500
      task_id  VM_ID   Start_time  Finish_time  Exec_time
0           0      4     0.000000     5.714286   5.714286
1           1      3     0.000000     5.714286   5.714286
2           2      2     0.000000     8.000000   8.000000
3           3      4     5.714286    11.428571   5.714286
4           4      4    11.428571    17.142857   5.714286
...       ...    ...          ...          ...        ...
2495     2495      2  2760.000000  2768.000000   8.000000
2496     2496      4  8502.857143  8508.571429   5.714286
2497     2497      4  8508.571429  8514.285714   5.714286
2498     2498      2  2768.000000  2776.000000   8.000000
2499     2499      3  2754.285714  2760.000000   5.714286

[2500 rows x 5 columns]

<ipython-input-8-e9652d172dbe>:97: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2_exe.insert(1, f,exe1)
<ipython-input-8-e9652d172dbe>:98: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2_start.insert(1, f,average_start)
<ipython-input-8-e9652d172dbe>:99: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2_finish.insert(1, f,average_finish)
<ipython-input-8-e9652d172dbe>:100: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2_aexe.insert(1, f,average_exe)
<ipython-input-8-e9652d172dbe>:101: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2_util.insert(1, f,utili1)
<ipython-input-8-e9652d172dbe>:102: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2_power.insert(1, f,power)

100
272.0
100
    task_id  VM_ID  Start_time  Finish_time  Exec_time
0         0      2    0.000000     8.000000   8.000000
1         1      1    0.000000    16.000000  16.000000
2         2      3    0.000000     5.714286   5.714286
3         3      3    5.714286    11.428571   5.714286
4         4      2    8.000000    16.000000   8.000000
..      ...    ...         ...          ...        ...
95       95      3  200.000000   205.714286   5.714286
96       96      2  240.000000   248.000000   8.000000
97       97      3  205.714286   211.428571   5.714286
98       98      4   80.000000    85.714286   5.714286
99       99      0   80.000000    85.714286   5.714286

[100 rows x 5 columns]
500
2224.0
500
     task_id  VM_ID  Start_time  Finish_time  Exec_time
0          0      3    0.000000     5.714286   5.714286
1          1      4    0.000000     5.714286   5.714286
2          2      4    5.714286    11.428571   5.714286
3          3      0    5.714286    11.428571   5.714286
4          4      3    5.714286    11.428571   5.714286
..       ...    ...         ...          ...        ...
495      495      4  417.142857   422.857143   5.714286
496      496      4  422.857143   428.571429   5.714286
497      497      3  817.142857   822.857143   5.714286
498      498      3  822.857143   828.571429   5.714286
499      499      3  828.571429   834.285714   5.714286

[500 rows x 5 columns]
1000
An exception occurred local variable 'start' referenced before assignment
1500
7728.0
1500
      task_id  VM_ID   Start_time  Finish_time  Exec_time
0           0      4     0.000000     5.714286   5.714286
1           1      0     0.000000     5.714286   5.714286
2           2      3     0.000000     5.714286   5.714286
3           3      4     5.714286    11.428571   5.714286
4           4      2     0.000000     8.000000   8.000000
...       ...    ...          ...          ...        ...
1495     1495      1  7696.000000  7712.000000  16.000000
1496     1496      2  3024.000000  3032.000000   8.000000
1497     1497      0  3024.000000  3032.000000   8.000000
1498     1498      3  2434.285714  2440.000000   5.714286
1499     1499      2  3032.000000  3040.000000   8.000000

[1500 rows x 5 columns]
2000
10480.0
2000
      task_id  VM_ID  Start_time   Finish_time  Exec_time
0           0      2         0.0      8.000000   8.000000
1           1      0         0.0      8.000000   8.000000
2           2      1        16.0     32.000000  16.000000
3           3      4         0.0      5.714286   5.714286
4           4      0         0.0      5.714286   5.714286
...       ...    ...         ...           ...        ...
1995     1995      1     10416.0  10432.000000  16.000000
1996     1996      2      4400.0   4408.000000   8.000000
1997     1997      1     10432.0  10448.000000  16.000000
1998     1998      1     10448.0  10464.000000  16.000000
1999     1999      1     10464.0  10480.000000  16.000000

[2000 rows x 5 columns]
2500
13296.0
2500
      task_id  VM_ID    Start_time   Finish_time  Exec_time
0           0      2      0.000000      8.000000   8.000000
1           1      3      0.000000      5.714286   5.714286
2           2      3      5.714286     11.428571   5.714286
3           3      4      0.000000      5.714286   5.714286
4           4      1      0.000000     16.000000  16.000000
...       ...    ...           ...           ...        ...
2495     2495      3   3851.428571   3857.142857   5.714286
2496     2496      4   1857.142857   1862.857143   5.714286
2497     2497      2   5336.000000   5344.000000   8.000000
2498     2498      1  13264.000000  13280.000000  16.000000
2499     2499      1  13280.000000  13296.000000  16.000000

[2500 rows x 5 columns]
algo not found
100
194.2857142857143
100
    task_id  VM_ID  Start_time  Finish_time  Exec_time
0         0      4    0.000000     5.714286   5.714286
1         1      4    5.714286    11.428571   5.714286
2         2      4   11.428571    17.142857   5.714286
3         3      4   17.142857    22.857143   5.714286
4         4      4   22.857143    28.571429   5.714286
..      ...    ...         ...          ...        ...
95       95      1  160.000000   176.000000  16.000000
96       96      3  171.428571   177.142857   5.714286
97       97      4  188.571429   194.285714   5.714286
98       98      3  177.142857   182.857143   5.714286
99       99      3  182.857143   188.571429   5.714286

[100 rows x 5 columns]
500
992.0
500
     task_id  VM_ID  Start_time  Finish_time  Exec_time
0          0      4    0.000000     5.714286   5.714286
1          1      4    5.714286    11.428571   5.714286
2          2      4   11.428571    17.142857   5.714286
3          3      4   17.142857    22.857143   5.714286
4          4      4   22.857143    28.571429   5.714286
..       ...    ...         ...          ...        ...
495      495      3  880.000000   885.714286   5.714286
496      496      3  885.714286   891.428571   5.714286
497      497      1  960.000000   976.000000  16.000000
498      498      0  960.000000   976.000000  16.000000
499      499      2  864.000000   872.000000   8.000000

[500 rows x 5 columns]
1000
2257.142857142867
1000
     task_id  VM_ID   Start_time  Finish_time  Exec_time
0          0      4     0.000000     5.714286   5.714286
1          1      4     5.714286    11.428571   5.714286
2          2      4    11.428571    17.142857   5.714286
3          3      4    17.142857    22.857143   5.714286
4          4      4    22.857143    28.571429   5.714286
..       ...    ...          ...          ...        ...
995      995      4  2228.571429  2234.285714   5.714286
996      996      4  2234.285714  2240.000000   5.714286
997      997      4  2240.000000  2245.714286   5.714286
998      998      4  2245.714286  2251.428571   5.714286
999      999      4  2251.428571  2257.142857   5.714286

[1000 rows x 5 columns]
1500
3754.285714285741
1500
      task_id  VM_ID   Start_time  Finish_time  Exec_time
0           0      3     0.000000     5.714286   5.714286
1           1      3     5.714286    11.428571   5.714286
2           2      3    11.428571    17.142857   5.714286
3           3      3    17.142857    22.857143   5.714286
4           4      2     0.000000     8.000000   8.000000
...       ...    ...          ...          ...        ...
1495     1495      2  1320.000000  1328.000000   8.000000
1496     1496      4  3731.428571  3737.142857   5.714286
1497     1497      4  3737.142857  3742.857143   5.714286
1498     1498      4  3742.857143  3748.571429   5.714286
1499     1499      4  3748.571429  3754.285714   5.714286

[1500 rows x 5 columns]
2000
4240.000000000021
2000
      task_id  VM_ID   Start_time  Finish_time  Exec_time
0           0      4     0.000000     5.714286   5.714286
1           1      4     5.714286    11.428571   5.714286
2           2      4    11.428571    17.142857   5.714286
3           3      4    17.142857    22.857143   5.714286
4           4      4    22.857143    28.571429   5.714286
...       ...    ...          ...          ...        ...
1995     1995      3  3908.571429  3914.285714   5.714286
1996     1996      3  3914.285714  3920.000000   5.714286
1997     1997      4  4228.571429  4234.285714   5.714286
1998     1998      3  3920.000000  3925.714286   5.714286
1999     1999      4  4234.285714  4240.000000   5.714286

[2000 rows x 5 columns]
2500
6005.714285714186
2500
      task_id  VM_ID   Start_time  Finish_time  Exec_time
0           0      4     0.000000     5.714286   5.714286
1           1      4     5.714286    11.428571   5.714286
2           2      4    11.428571    17.142857   5.714286
3           3      4    17.142857    22.857143   5.714286
4           4      4    22.857143    28.571429   5.714286
...       ...    ...          ...          ...        ...
2495     2495      4  5977.142857  5982.857143   5.714286
2496     2496      4  5982.857143  5988.571429   5.714286
2497     2497      4  5988.571429  5994.285714   5.714286
2498     2498      4  5994.285714  6000.000000   5.714286
2499     2499      4  6000.000000  6005.714286   5.714286

[2500 rows x 5 columns]

<ipython-input-8-e9652d172dbe>:97: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2_exe.insert(1, f,exe1)
<ipython-input-8-e9652d172dbe>:98: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2_start.insert(1, f,average_start)
<ipython-input-8-e9652d172dbe>:99: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2_finish.insert(1, f,average_finish)
<ipython-input-8-e9652d172dbe>:100: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2_aexe.insert(1, f,average_exe)
<ipython-input-8-e9652d172dbe>:101: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2_util.insert(1, f,utili1)
<ipython-input-8-e9652d172dbe>:102: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2_power.insert(1, f,power)

100
285.71428571428584
100
    task_id  VM_ID  Start_time  Finish_time  Exec_time
0         0      4    0.000000     5.714286   5.714286
1         1      3    0.000000     5.714286   5.714286
2         2      0    0.000000     5.714286   5.714286
3         3      2    0.000000     8.000000   8.000000
4         4      3    5.714286    11.428571   5.714286
..      ...    ...         ...          ...        ...
95       95      3  125.714286   131.428571   5.714286
96       96      4  268.571429   274.285714   5.714286
97       97      4  274.285714   280.000000   5.714286
98       98      4  280.000000   285.714286   5.714286
99       99      3  131.428571   137.142857   5.714286

[100 rows x 5 columns]
500
1645.7142857142887
500
     task_id  VM_ID   Start_time  Finish_time  Exec_time
0          0      2     0.000000     8.000000   8.000000
1          1      3     0.000000     5.714286   5.714286
2          2      4     0.000000     5.714286   5.714286
3          3      4     5.714286    11.428571   5.714286
4          4      4    11.428571    17.142857   5.714286
..       ...    ...          ...          ...        ...
495      495      4  1628.571429  1634.285714   5.714286
496      496      4  1634.285714  1640.000000   5.714286
497      497      3   605.714286   611.428571   5.714286
498      498      1   640.000000   656.000000  16.000000
499      499      4  1640.000000  1645.714286   5.714286

[500 rows x 5 columns]
1000
2205.714285714295
1000
     task_id  VM_ID   Start_time  Finish_time  Exec_time
0          0      4     0.000000     5.714286   5.714286
1          1      1     0.000000    16.000000  16.000000
2          2      2     0.000000     8.000000   8.000000
3          3      2     8.000000    16.000000   8.000000
4          4      3     0.000000     5.714286   5.714286
..       ...    ...          ...          ...        ...
995      995      4  2194.285714  2200.000000   5.714286
996      996      4  2200.000000  2205.714286   5.714286
997      997      2  1840.000000  1848.000000   8.000000
998      998      1  1824.000000  1840.000000  16.000000
999      999      1  1840.000000  1856.000000  16.000000

[1000 rows x 5 columns]
1500
3360.0000000000223
1500
      task_id  VM_ID   Start_time  Finish_time  Exec_time
0           0      1     0.000000    16.000000  16.000000
1           1      3     0.000000     5.714286   5.714286
2           2      3     5.714286    11.428571   5.714286
3           3      4     0.000000     5.714286   5.714286
4           4      4     5.714286    11.428571   5.714286
...       ...    ...          ...          ...        ...
1495     1495      1  2736.000000  2752.000000  16.000000
1496     1496      3  2211.428571  2217.142857   5.714286
1497     1497      3  2217.142857  2222.857143   5.714286
1498     1498      3  2222.857143  2228.571429   5.714286
1499     1499      2  2792.000000  2800.000000   8.000000

[1500 rows x 5 columns]
2000
6788.571428571276
2000
      task_id  VM_ID   Start_time  Finish_time  Exec_time
0           0      2     0.000000     8.000000   8.000000
1           1      1     0.000000    16.000000  16.000000
2           2      4     0.000000     5.714286   5.714286
3           3      4     5.714286    11.428571   5.714286
4           4      4    11.428571    17.142857   5.714286
...       ...    ...          ...          ...        ...
1995     1995      4  6771.428571  6777.142857   5.714286
1996     1996      4  6777.142857  6782.857143   5.714286
1997     1997      3  2217.142857  2222.857143   5.714286
1998     1998      4  6782.857143  6788.571429   5.714286
1999     1999      2  2144.000000  2152.000000   8.000000

[2000 rows x 5 columns]
2500
8314.285714285477
2500
      task_id  VM_ID   Start_time  Finish_time  Exec_time
0           0      3     0.000000     5.714286   5.714286
1           1      4     0.000000     5.714286   5.714286
2           2      4     5.714286    11.428571   5.714286
3           3      4    11.428571    17.142857   5.714286
4           4      4    17.142857    22.857143   5.714286
...       ...    ...          ...          ...        ...
2495     2495      4  8308.571429  8314.285714   5.714286
2496     2496      2  2824.000000  2832.000000   8.000000
2497     2497      3  2857.142857  2862.857143   5.714286
2498     2498      1  3008.000000  3024.000000  16.000000
2499     2499      3  2862.857143  2868.571429   5.714286

[2500 rows x 5 columns]
100

<ipython-input-8-e9652d172dbe>:97: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2_exe.insert(1, f,exe1)
<ipython-input-8-e9652d172dbe>:98: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2_start.insert(1, f,average_start)
<ipython-input-8-e9652d172dbe>:99: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2_finish.insert(1, f,average_finish)
<ipython-input-8-e9652d172dbe>:100: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2_aexe.insert(1, f,average_exe)
<ipython-input-8-e9652d172dbe>:101: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2_util.insert(1, f,utili1)
<ipython-input-8-e9652d172dbe>:102: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2_power.insert(1, f,power)

An exception occurred local variable 'start' referenced before assignment
500
2608.0
500
     task_id  VM_ID   Start_time  Finish_time  Exec_time
0          0      2     0.000000     8.000000   8.000000
1          1      2     8.000000    16.000000   8.000000
2          2      0     8.000000    16.000000   8.000000
3          3      3     0.000000     5.714286   5.714286
4          4      2    16.000000    24.000000   8.000000
..       ...    ...          ...          ...        ...
495      495      4   360.000000   365.714286   5.714286
496      496      1  2576.000000  2592.000000  16.000000
497      497      1  2592.000000  2608.000000  16.000000
498      498      3   794.285714   800.000000   5.714286
499      499      2  1056.000000  1064.000000   8.000000

[500 rows x 5 columns]
1000
5600.0
1000
     task_id  VM_ID   Start_time  Finish_time  Exec_time
0          0      2     0.000000     8.000000   8.000000
1          1      3     0.000000     5.714286   5.714286
2          2      2     8.000000    16.000000   8.000000
3          3      1     0.000000    16.000000  16.000000
4          4      2    16.000000    24.000000   8.000000
..       ...    ...          ...          ...        ...
995      995      3  1394.285714  1400.000000   5.714286
996      996      4   760.000000   765.714286   5.714286
997      997      1  5584.000000  5600.000000  16.000000
998      998      4   765.714286   771.428571   5.714286
999      999      2  2152.000000  2160.000000   8.000000

[1000 rows x 5 columns]
1500
8480.0
1500
      task_id  VM_ID   Start_time  Finish_time  Exec_time
0           0      2     0.000000     8.000000   8.000000
1           1      1     0.000000    16.000000  16.000000
2           2      3     0.000000     5.714286   5.714286
3           3      4     0.000000     5.714286   5.714286
4           4      4     5.714286    11.428571   5.714286
...       ...    ...          ...          ...        ...
1495     1495      1  8400.000000  8416.000000  16.000000
1496     1496      1  8416.000000  8432.000000  16.000000
1497     1497      0  8416.000000  8432.000000  16.000000
1498     1498      1  8448.000000  8464.000000  16.000000
1499     1499      0  8448.000000  8464.000000  16.000000

[1500 rows x 5 columns]
2000
11232.0
2000
      task_id  VM_ID    Start_time   Finish_time  Exec_time
0           0      3      0.000000      5.714286   5.714286
1           1      2      0.000000      8.000000   8.000000
2           2      1      0.000000     16.000000  16.000000
3           3      3      5.714286     11.428571   5.714286
4           4      1     16.000000     32.000000  16.000000
...       ...    ...           ...           ...        ...
1995     1995      2   3856.000000   3864.000000   8.000000
1996     1996      2   3864.000000   3872.000000   8.000000
1997     1997      4   1480.000000   1485.714286   5.714286
1998     1998      0   1480.000000   1485.714286   5.714286
1999     1999      1  11216.000000  11232.000000  16.000000

[2000 rows x 5 columns]
2500
14224.0
2500
      task_id  VM_ID    Start_time   Finish_time  Exec_time
0           0      4      0.000000      5.714286   5.714286
1           1      2      0.000000      8.000000   8.000000
2           2      1      0.000000     16.000000  16.000000
3           3      3      0.000000      5.714286   5.714286
4           4      2      8.000000     16.000000   8.000000
...       ...    ...           ...           ...        ...
2495     2495      3   3720.000000   3725.714286   5.714286
2496     2496      2   4936.000000   4944.000000   8.000000
2497     2497      3   3725.714286   3731.428571   5.714286
2498     2498      2   4944.000000   4952.000000   8.000000
2499     2499      1  14208.000000  14224.000000  16.000000

[2500 rows x 5 columns]
algo not found
100
208.0
100
    task_id  VM_ID  Start_time  Finish_time  Exec_time
0         0      1    0.000000    16.000000  16.000000
1         1      4    0.000000     5.714286   5.714286
2         2      3    0.000000     5.714286   5.714286
3         3      2    0.000000     8.000000   8.000000
4         4      2    8.000000    16.000000   8.000000
..      ...    ...         ...          ...        ...
95       95      4  177.142857   182.857143   5.714286
96       96      3  160.000000   165.714286   5.714286
97       97      3  165.714286   171.428571   5.714286
98       98      3  171.428571   177.142857   5.714286
99       99      4  182.857143   188.571429   5.714286

[100 rows x 5 columns]
500
1856.0
500
     task_id  VM_ID   Start_time  Finish_time  Exec_time
0          0      3     0.000000     5.714286   5.714286
1          1      2     0.000000     8.000000   8.000000
2          2      3     5.714286    11.428571   5.714286
3          3      2     8.000000    16.000000   8.000000
4          4      2    16.000000    24.000000   8.000000
..       ...    ...          ...          ...        ...
495      495      1  1824.000000  1840.000000  16.000000
496      496      3   840.000000   845.714286   5.714286
497      497      2  1384.000000  1392.000000   8.000000
498      498      3   845.714286   851.428571   5.714286
499      499      0   845.714286   851.428571   5.714286

[500 rows x 5 columns]
1000
4432.0
1000
     task_id  VM_ID   Start_time  Finish_time  Exec_time
0          0      2     0.000000     8.000000   8.000000
1          1      1     0.000000    16.000000  16.000000
2          2      0     0.000000    16.000000  16.000000
3          3      0     0.000000    16.000000  16.000000
4          4      3     0.000000     5.714286   5.714286
..       ...    ...          ...          ...        ...
995      995      3  1577.142857  1582.857143   5.714286
996      996      2  2528.000000  2536.000000   8.000000
997      997      0  2528.000000  2536.000000   8.000000
998      998      2  2536.000000  2544.000000   8.000000
999      999      2  2544.000000  2552.000000   8.000000

[1000 rows x 5 columns]
1500
6288.0
1500
      task_id  VM_ID   Start_time  Finish_time  Exec_time
0           0      3     0.000000     5.714286   5.714286
1           1      2     0.000000     8.000000   8.000000
2           2      2     8.000000    16.000000   8.000000
3           3      2    16.000000    24.000000   8.000000
4           4      2    24.000000    32.000000   8.000000
...       ...    ...          ...          ...        ...
1495     1495      2  4704.000000  4712.000000   8.000000
1496     1496      2  4712.000000  4720.000000   8.000000
1497     1497      3  2377.142857  2382.857143   5.714286
1498     1498      2  4720.000000  4728.000000   8.000000
1499     1499      3  2382.857143  2388.571429   5.714286

[1500 rows x 5 columns]
2000
8960.0
2000
      task_id  VM_ID   Start_time  Finish_time  Exec_time
0           0      2     0.000000     8.000000   8.000000
1           1      2     8.000000    16.000000   8.000000
2           2      2    16.000000    24.000000   8.000000
3           3      3     0.000000     5.714286   5.714286
4           4      3     5.714286    11.428571   5.714286
...       ...    ...          ...          ...        ...
1995     1995      2  6168.000000  6176.000000   8.000000
1996     1996      1  8944.000000  8960.000000  16.000000
1997     1997      2  6176.000000  6184.000000   8.000000
1998     1998      2  6184.000000  6192.000000   8.000000
1999     1999      3  2885.714286  2891.428571   5.714286

[2000 rows x 5 columns]
2500
10784.0
2500
      task_id  VM_ID    Start_time   Finish_time  Exec_time
0           0      2      0.000000      8.000000   8.000000
1           1      1      0.000000     16.000000  16.000000
2           2      0      0.000000     16.000000  16.000000
3           3      3      0.000000      5.714286   5.714286
4           4      2      8.000000     16.000000   8.000000
...       ...    ...           ...           ...        ...
2495     2495      3   3725.714286   3731.428571   5.714286
2496     2496      4    680.000000    685.714286   5.714286
2497     2497      2   8416.000000   8424.000000   8.000000
2498     2498      0   8416.000000   8424.000000   8.000000
2499     2499      1  10768.000000  10784.000000  16.000000

[2500 rows x 5 columns]

<ipython-input-8-e9652d172dbe>:97: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2_exe.insert(1, f,exe1)
<ipython-input-8-e9652d172dbe>:98: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2_start.insert(1, f,average_start)
<ipython-input-8-e9652d172dbe>:99: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2_finish.insert(1, f,average_finish)
<ipython-input-8-e9652d172dbe>:100: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2_aexe.insert(1, f,average_exe)
<ipython-input-8-e9652d172dbe>:101: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2_util.insert(1, f,utili1)
<ipython-input-8-e9652d172dbe>:102: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2_power.insert(1, f,power)

100
416.0
100
    task_id  VM_ID  Start_time  Finish_time  Exec_time
0         0      3    0.000000     5.714286   5.714286
1         1      0    0.000000     5.714286   5.714286
2         2      2    0.000000     8.000000   8.000000
3         3      0    0.000000     8.000000   8.000000
4         4      3    5.714286    11.428571   5.714286
..      ...    ...         ...          ...        ...
95       95      3  154.285714   160.000000   5.714286
96       96      3  160.000000   165.714286   5.714286
97       97      2  208.000000   216.000000   8.000000
98       98      1  400.000000   416.000000  16.000000
99       99      4   97.142857   102.857143   5.714286

[100 rows x 5 columns]
500
2560.0
500
     task_id  VM_ID   Start_time  Finish_time  Exec_time
0          0      3     0.000000     5.714286   5.714286
1          1      3     5.714286    11.428571   5.714286
2          2      3    11.428571    17.142857   5.714286
3          3      1     0.000000    16.000000  16.000000
4          4      3    17.142857    22.857143   5.714286
..       ...    ...          ...          ...        ...
495      495      0   992.000000  1000.000000   8.000000
496      496      1  2528.000000  2544.000000  16.000000
497      497      2  1000.000000  1008.000000   8.000000
498      498      2  1008.000000  1016.000000   8.000000
499      499      1  2544.000000  2560.000000  16.000000

[500 rows x 5 columns]
1000
5504.0
1000
     task_id  VM_ID   Start_time  Finish_time  Exec_time
0          0      4     0.000000     5.714286   5.714286
1          1      3     0.000000     5.714286   5.714286
2          2      0     0.000000     5.714286   5.714286
3          3      3     5.714286    11.428571   5.714286
4          4      3    11.428571    17.142857   5.714286
..       ...    ...          ...          ...        ...
995      995      3  1474.285714  1480.000000   5.714286
996      996      1  5472.000000  5488.000000  16.000000
997      997      3  1480.000000  1485.714286   5.714286
998      998      2  2208.000000  2216.000000   8.000000
999      999      1  5488.000000  5504.000000  16.000000

[1000 rows x 5 columns]
1500
An exception occurred local variable 'start' referenced before assignment
2000
11072.0
2000
      task_id  VM_ID    Start_time   Finish_time  Exec_time
0           0      1      0.000000     16.000000  16.000000
1           1      4      0.000000      5.714286   5.714286
2           2      4      5.714286     11.428571   5.714286
3           3      1     16.000000     32.000000  16.000000
4           4      3      0.000000      5.714286   5.714286
...       ...    ...           ...           ...        ...
1995     1995      1  11024.000000  11040.000000  16.000000
1996     1996      3   2817.142857   2822.857143   5.714286
1997     1997      4   1537.142857   1542.857143   5.714286
1998     1998      1  11040.000000  11056.000000  16.000000
1999     1999      1  11056.000000  11072.000000  16.000000

[2000 rows x 5 columns]
2500
14176.0
2500
      task_id  VM_ID   Start_time  Finish_time  Exec_time
0           0      3     0.000000     5.714286   5.714286
1           1      4     0.000000     5.714286   5.714286
2           2      1     0.000000    16.000000  16.000000
3           3      1    16.000000    32.000000  16.000000
4           4      4     5.714286    11.428571   5.714286
...       ...    ...          ...          ...        ...
2495     2495      0  1777.142857  1782.857143   5.714286
2496     2496      4  1782.857143  1788.571429   5.714286
2497     2497      3  3645.714286  3651.428571   5.714286
2498     2498      4  1788.571429  1794.285714   5.714286
2499     2499      2  5280.000000  5288.000000   8.000000

[2500 rows x 5 columns]
algo not found
100
256.0
100
    task_id  VM_ID  Start_time  Finish_time  Exec_time
0         0      4    0.000000     5.714286   5.714286
1         1      0    0.000000     5.714286   5.714286
2         2      2    0.000000     8.000000   8.000000
3         3      3    0.000000     5.714286   5.714286
4         4      2    8.000000    16.000000   8.000000
..      ...    ...         ...          ...        ...
95       95      2  240.000000   248.000000   8.000000
96       96      2  248.000000   256.000000   8.000000
97       97      3  200.000000   205.714286   5.714286
98       98      3  205.714286   211.428571   5.714286
99       99      4   80.000000    85.714286   5.714286

[100 rows x 5 columns]
500
1376.0
500
     task_id  VM_ID   Start_time  Finish_time  Exec_time
0          0      3     0.000000     5.714286   5.714286
1          1      3     5.714286    11.428571   5.714286
2          2      1     0.000000    16.000000  16.000000
3          3      3    11.428571    17.142857   5.714286
4          4      3    17.142857    22.857143   5.714286
..       ...    ...          ...          ...        ...
495      495      3  1325.714286  1331.428571   5.714286
496      496      3  1331.428571  1337.142857   5.714286
497      497      2  1360.000000  1368.000000   8.000000
498      498      3  1337.142857  1342.857143   5.714286
499      499      2  1368.000000  1376.000000   8.000000

[500 rows x 5 columns]
1000
3376.0
1000
     task_id  VM_ID   Start_time  Finish_time  Exec_time
0          0      2     0.000000     8.000000   8.000000
1          1      2     8.000000    16.000000   8.000000
2          2      3     0.000000     5.714286   5.714286
3          3      3     5.714286    11.428571   5.714286
4          4      3    11.428571    17.142857   5.714286
..       ...    ...          ...          ...        ...
995      995      2  3352.000000  3360.000000   8.000000
996      996      2  3360.000000  3368.000000   8.000000
997      997      2  3368.000000  3376.000000   8.000000
998      998      3  2022.857143  2028.571429   5.714286
999      999      4    68.571429    74.285714   5.714286

[1000 rows x 5 columns]
1500
5176.0
1500
      task_id  VM_ID   Start_time  Finish_time  Exec_time
0           0      3     0.000000     5.714286   5.714286
1           1      3     5.714286    11.428571   5.714286
2           2      2     0.000000     8.000000   8.000000
3           3      2     8.000000    16.000000   8.000000
4           4      2    16.000000    24.000000   8.000000
...       ...    ...          ...          ...        ...
1495     1495      1  5104.000000  5120.000000  16.000000
1496     1496      2  5152.000000  5160.000000   8.000000
1497     1497      2  5160.000000  5168.000000   8.000000
1498     1498      2  5168.000000  5176.000000   8.000000
1499     1499      1  5120.000000  5136.000000  16.000000

[1500 rows x 5 columns]
2000
7256.0
2000
      task_id  VM_ID   Start_time  Finish_time  Exec_time
0           0      3     0.000000     5.714286   5.714286
1           1      3     5.714286    11.428571   5.714286
2           2      1     0.000000    16.000000  16.000000
3           3      1    16.000000    32.000000  16.000000
4           4      1    32.000000    48.000000  16.000000
...       ...    ...          ...          ...        ...
1995     1995      2  7240.000000  7248.000000   8.000000
1996     1996      1  7216.000000  7232.000000  16.000000
1997     1997      2  7248.000000  7256.000000   8.000000
1998     1998      3  3582.857143  3588.571429   5.714286
1999     1999      3  3588.571429  3594.285714   5.714286

[2000 rows x 5 columns]
2500
8992.0
2500
      task_id  VM_ID   Start_time  Finish_time  Exec_time
0           0      2     0.000000     8.000000   8.000000
1           1      2     8.000000    16.000000   8.000000
2           2      3     0.000000     5.714286   5.714286
3           3      1     0.000000    16.000000  16.000000
4           4      2    16.000000    24.000000   8.000000
...       ...    ...          ...          ...        ...
2495     2495      2  8976.000000  8984.000000   8.000000
2496     2496      3  4582.857143  4588.571429   5.714286
2497     2497      3  4588.571429  4594.285714   5.714286
2498     2498      1  8912.000000  8928.000000  16.000000
2499     2499      2  8984.000000  8992.000000   8.000000

[2500 rows x 5 columns]

<ipython-input-8-e9652d172dbe>:97: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2_exe.insert(1, f,exe1)
<ipython-input-8-e9652d172dbe>:98: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2_start.insert(1, f,average_start)
<ipython-input-8-e9652d172dbe>:99: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2_finish.insert(1, f,average_finish)
<ipython-input-8-e9652d172dbe>:100: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2_aexe.insert(1, f,average_exe)
<ipython-input-8-e9652d172dbe>:101: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2_util.insert(1, f,utili1)
<ipython-input-8-e9652d172dbe>:102: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2_power.insert(1, f,power)

100
200.00000000000003
100
    task_id  VM_ID  Start_time  Finish_time  Exec_time
0         0      2    0.000000     8.000000   8.000000
1         1      3    0.000000     5.714286   5.714286
2         2      4    0.000000     5.714286   5.714286
3         3      1    0.000000    16.000000  16.000000
4         4      4    5.714286    11.428571   5.714286
..      ...    ...         ...          ...        ...
95       95      4  194.285714   200.000000   5.714286
96       96      3  182.857143   188.571429   5.714286
97       97      0  182.857143   188.571429   5.714286
98       98      2  160.000000   168.000000   8.000000
99       99      0  160.000000   168.000000   8.000000

[100 rows x 5 columns]
500
2160.0
500
     task_id  VM_ID   Start_time  Finish_time  Exec_time
0          0      1     0.000000    16.000000  16.000000
1          1      3     0.000000     5.714286   5.714286
2          2      2     0.000000     8.000000   8.000000
3          3      4     0.000000     5.714286   5.714286
4          4      0     0.000000     5.714286   5.714286
..       ...    ...          ...          ...        ...
495      495      1  2128.000000  2144.000000  16.000000
496      496      4   771.428571   777.142857   5.714286
497      497      4   777.142857   782.857143   5.714286
498      498      3   714.285714   720.000000   5.714286
499      499      1  2144.000000  2160.000000  16.000000

[500 rows x 5 columns]
1000
4928.0
1000
     task_id  VM_ID   Start_time  Finish_time  Exec_time
0          0      4     0.000000     5.714286   5.714286
1          1      0     0.000000     5.714286   5.714286
2          2      4     5.714286    11.428571   5.714286
3          3      3     0.000000     5.714286   5.714286
4          4      0     0.000000     5.714286   5.714286
..       ...    ...          ...          ...        ...
995      995      4  1542.857143  1548.571429   5.714286
996      996      3  1177.142857  1182.857143   5.714286
997      997      3  1182.857143  1188.571429   5.714286
998      998      2  1688.000000  1696.000000   8.000000
999      999      4  1548.571429  1554.285714   5.714286

[1000 rows x 5 columns]
1500
7984.0
1500
      task_id  VM_ID   Start_time  Finish_time  Exec_time
0           0      1     0.000000    16.000000  16.000000
1           1      4     0.000000     5.714286   5.714286
2           2      0     0.000000     5.714286   5.714286
3           3      4     5.714286    11.428571   5.714286
4           4      2     0.000000     8.000000   8.000000
...       ...    ...          ...          ...        ...
1495     1495      2  3000.000000  3008.000000   8.000000
1496     1496      3  1902.857143  1908.571429   5.714286
1497     1497      2  3008.000000  3016.000000   8.000000
1498     1498      4  1645.714286  1651.428571   5.714286
1499     1499      3  1908.571429  1914.285714   5.714286

[1500 rows x 5 columns]
2000
11008.0
2000
      task_id  VM_ID  Start_time   Finish_time  Exec_time
0           0      2         0.0      8.000000   8.000000
1           1      1         0.0     16.000000  16.000000
2           2      2         8.0     16.000000   8.000000
3           3      0         8.0     16.000000   8.000000
4           4      4         0.0      5.714286   5.714286
...       ...    ...         ...           ...        ...
1995     1995      1     10976.0  10992.000000  16.000000
1996     1996      2      4088.0   4096.000000   8.000000
1997     1997      0      4088.0   4096.000000   8.000000
1998     1998      2      4096.0   4104.000000   8.000000
1999     1999      2      4104.0   4112.000000   8.000000

[2000 rows x 5 columns]
2500
An exception occurred local variable 'start' referenced before assignment
algo not found
100
188.57142857142858
100
    task_id  VM_ID  Start_time  Finish_time  Exec_time
0         0      3    0.000000     5.714286   5.714286
1         1      2    0.000000     8.000000   8.000000
2         2      4    0.000000     5.714286   5.714286
3         3      2    8.000000    16.000000   8.000000
4         4      4    5.714286    11.428571   5.714286
..      ...    ...         ...          ...        ...
95       95      2  160.000000   168.000000   8.000000
96       96      3  182.857143   188.571429   5.714286
97       97      4  182.857143   188.571429   5.714286
98       98      2  168.000000   176.000000   8.000000
99       99      2  176.000000   184.000000   8.000000

[100 rows x 5 columns]
500
1456.0
500
     task_id  VM_ID   Start_time  Finish_time  Exec_time
0          0      2     0.000000     8.000000   8.000000
1          1      2     8.000000    16.000000   8.000000
2          2      3     0.000000     5.714286   5.714286
3          3      2    16.000000    24.000000   8.000000
4          4      2    24.000000    32.000000   8.000000
..       ...    ...          ...          ...        ...
495      495      1  1424.000000  1440.000000  16.000000
496      496      3  1017.142857  1022.857143   5.714286
497      497      3  1022.857143  1028.571429   5.714286
498      498      2  1376.000000  1384.000000   8.000000
499      499      1  1440.000000  1456.000000  16.000000

[500 rows x 5 columns]
1000
3408.0
1000
     task_id  VM_ID   Start_time  Finish_time  Exec_time
0          0      3     0.000000     5.714286   5.714286
1          1      1     0.000000    16.000000  16.000000
2          2      1    16.000000    32.000000  16.000000
3          3      3     5.714286    11.428571   5.714286
4          4      3    11.428571    17.142857   5.714286
..       ...    ...          ...          ...        ...
995      995      3  1685.714286  1691.428571   5.714286
996      996      3  1691.428571  1697.142857   5.714286
997      997      2  3392.000000  3400.000000   8.000000
998      998      2  3400.000000  3408.000000   8.000000
999      999      1  3344.000000  3360.000000  16.000000

[1000 rows x 5 columns]
1500
5584.0
1500
      task_id  VM_ID   Start_time  Finish_time  Exec_time
0           0      3     0.000000     5.714286   5.714286
1           1      4     0.000000     5.714286   5.714286
2           2      3     5.714286    11.428571   5.714286
3           3      2     0.000000     8.000000   8.000000
4           4      3    11.428571    17.142857   5.714286
...       ...    ...          ...          ...        ...
1495     1495      2  4592.000000  4600.000000   8.000000
1496     1496      1  5568.000000  5584.000000  16.000000
1497     1497      3  2531.428571  2537.142857   5.714286
1498     1498      3  2537.142857  2542.857143   5.714286
1499     1499      2  4600.000000  4608.000000   8.000000

[1500 rows x 5 columns]
2000
An exception occurred local variable 'start' referenced before assignment
2500
9424.0
2500
      task_id  VM_ID  Start_time  Finish_time  Exec_time
0           0      1         0.0    16.000000  16.000000
1           1      3         0.0     5.714286   5.714286
2           2      2         0.0     8.000000   8.000000
3           3      2         8.0    16.000000   8.000000
4           4      2        16.0    24.000000   8.000000
...       ...    ...         ...          ...        ...
2495     2495      0      8656.0  8664.000000   8.000000
2496     2496      2      8664.0  8672.000000   8.000000
2497     2497      3      4000.0  4005.714286   5.714286
2498     2498      2      8672.0  8680.000000   8.000000
2499     2499      0      8672.0  8680.000000   8.000000

[2500 rows x 5 columns]
algo not found
100
188.57142857142858
100
    task_id  VM_ID  Start_time  Finish_time  Exec_time
0         0      3    0.000000     5.714286   5.714286
1         1      4    0.000000     5.714286   5.714286
2         2      4    5.714286    11.428571   5.714286
3         3      3    5.714286    11.428571   5.714286
4         4      4   11.428571    17.142857   5.714286
..      ...    ...         ...          ...        ...
95       95      4  171.428571   177.142857   5.714286
96       96      3  177.142857   182.857143   5.714286
97       97      4  177.142857   182.857143   5.714286
98       98      3  182.857143   188.571429   5.714286
99       99      4  182.857143   188.571429   5.714286

[100 rows x 5 columns]
500
937.1428571428539
500
     task_id  VM_ID  Start_time  Finish_time  Exec_time
0          0      3    0.000000     5.714286   5.714286
1          1      2    0.000000     8.000000   8.000000
2          2      4    0.000000     5.714286   5.714286
3          3      4    5.714286    11.428571   5.714286
4          4      2    8.000000    16.000000   8.000000
..       ...    ...         ...          ...        ...
495      495      3  920.000000   925.714286   5.714286
496      496      3  925.714286   931.428571   5.714286
497      497      1  864.000000   880.000000  16.000000
498      498      3  931.428571   937.142857   5.714286
499      499      2  928.000000   936.000000   8.000000

[500 rows x 5 columns]
1000
2160.0
1000
     task_id  VM_ID   Start_time  Finish_time  Exec_time
0          0      4     0.000000     5.714286   5.714286
1          1      1     0.000000    16.000000  16.000000
2          2      4     5.714286    11.428571   5.714286
3          3      3     0.000000     5.714286   5.714286
4          4      4    11.428571    17.142857   5.714286
..       ...    ...          ...          ...        ...
995      995      3  2114.285714  2120.000000   5.714286
996      996      4  1274.285714  1280.000000   5.714286
997      997      3  2120.000000  2125.714286   5.714286
998      998      2  2152.000000  2160.000000   8.000000
999      999      3  2125.714286  2131.428571   5.714286

[1000 rows x 5 columns]
1500
3536.0
1500
      task_id  VM_ID   Start_time  Finish_time  Exec_time
0           0      4     0.000000     5.714286   5.714286
1           1      3     0.000000     5.714286   5.714286
2           2      3     5.714286    11.428571   5.714286
3           3      3    11.428571    17.142857   5.714286
4           4      3    17.142857    22.857143   5.714286
...       ...    ...          ...          ...        ...
1495     1495      3  3308.571429  3314.285714   5.714286
1496     1496      3  3314.285714  3320.000000   5.714286
1497     1497      2  3528.000000  3536.000000   8.000000
1498     1498      3  3320.000000  3325.714286   5.714286
1499     1499      4  1457.142857  1462.857143   5.714286

[1500 rows x 5 columns]
2000
5048.0
2000
      task_id  VM_ID   Start_time  Finish_time  Exec_time
0           0      2     0.000000     8.000000   8.000000
1           1      1     0.000000    16.000000  16.000000
2           2      2     8.000000    16.000000   8.000000
3           3      2    16.000000    24.000000   8.000000
4           4      3     0.000000     5.714286   5.714286
...       ...    ...          ...          ...        ...
1995     1995      4  1885.714286  1891.428571   5.714286
1996     1996      3  4154.285714  4160.000000   5.714286
1997     1997      4  1891.428571  1897.142857   5.714286
1998     1998      1  4912.000000  4928.000000  16.000000
1999     1999      4  1897.142857  1902.857143   5.714286

[2000 rows x 5 columns]
2500
6832.0
2500
      task_id  VM_ID   Start_time  Finish_time  Exec_time
0           0      3     0.000000     5.714286   5.714286
1           1      2     0.000000     8.000000   8.000000
2           2      3     5.714286    11.428571   5.714286
3           3      2     8.000000    16.000000   8.000000
4           4      3    11.428571    17.142857   5.714286
...       ...    ...          ...          ...        ...
2495     2495      3  4565.714286  4571.428571   5.714286
2496     2496      2  6688.000000  6696.000000   8.000000
2497     2497      2  6696.000000  6704.000000   8.000000
2498     2498      2  6704.000000  6712.000000   8.000000
2499     2499      3  4571.428571  4577.142857   5.714286

[2500 rows x 5 columns]

<ipython-input-8-e9652d172dbe>:97: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2_exe.insert(1, f,exe1)
<ipython-input-8-e9652d172dbe>:98: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2_start.insert(1, f,average_start)
<ipython-input-8-e9652d172dbe>:99: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2_finish.insert(1, f,average_finish)
<ipython-input-8-e9652d172dbe>:100: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2_aexe.insert(1, f,average_exe)
<ipython-input-8-e9652d172dbe>:101: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2_util.insert(1, f,utili1)
<ipython-input-8-e9652d172dbe>:102: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2_power.insert(1, f,power)

100
An exception occurred [Errno 2] No such file or directory: '/content/drive/MyDrive/colab/Cloudsim/exe/all/FA/sample_100_5.json'
500
2544.0
500
     task_id  VM_ID   Start_time  Finish_time  Exec_time
0          0      3     0.000000     5.714286   5.714286
1          1      1     0.000000    16.000000  16.000000
2          2      1    16.000000    32.000000  16.000000
3          3      4     0.000000     5.714286   5.714286
4          4      2     0.000000     8.000000   8.000000
..       ...    ...          ...          ...        ...
495      495      2  1144.000000  1152.000000   8.000000
496      496      1  2512.000000  2528.000000  16.000000
497      497      2  1152.000000  1160.000000   8.000000
498      498      3   805.714286   811.428571   5.714286
499      499      1  2528.000000  2544.000000  16.000000

[500 rows x 5 columns]
1000
5360.0
1000
     task_id  VM_ID   Start_time  Finish_time  Exec_time
0          0      3     0.000000     5.714286   5.714286
1          1      1     0.000000    16.000000  16.000000
2          2      3     5.714286    11.428571   5.714286
3          3      1    16.000000    32.000000  16.000000
4          4      3    11.428571    17.142857   5.714286
..       ...    ...          ...          ...        ...
995      995      1  5328.000000  5344.000000  16.000000
996      996      2  2096.000000  2104.000000   8.000000
997      997      1  5344.000000  5360.000000  16.000000
998      998      2  2104.000000  2112.000000   8.000000
999      999      3  1594.285714  1600.000000   5.714286

[1000 rows x 5 columns]
1500
8208.0
1500
      task_id  VM_ID   Start_time  Finish_time  Exec_time
0           0      2     0.000000     8.000000   8.000000
1           1      3     0.000000     5.714286   5.714286
2           2      3     5.714286    11.428571   5.714286
3           3      1     0.000000    16.000000  16.000000
4           4      1    16.000000    32.000000  16.000000
...       ...    ...          ...          ...        ...
1495     1495      3  2400.000000  2405.714286   5.714286
1496     1496      1  8160.000000  8176.000000  16.000000
1497     1497      1  8176.000000  8192.000000  16.000000
1498     1498      3  2405.714286  2411.428571   5.714286
1499     1499      1  8192.000000  8208.000000  16.000000

[1500 rows x 5 columns]
2000
11376.0
2000
      task_id  VM_ID    Start_time   Finish_time  Exec_time
0           0      2      0.000000      8.000000   8.000000
1           1      3      0.000000      5.714286   5.714286
2           2      3      5.714286     11.428571   5.714286
3           3      2      8.000000     16.000000   8.000000
4           4      2     16.000000     24.000000   8.000000
...       ...    ...           ...           ...        ...
1995     1995      1  11344.000000  11360.000000  16.000000
1996     1996      1  11360.000000  11376.000000  16.000000
1997     1997      3   3022.857143   3028.571429   5.714286
1998     1998      3   3028.571429   3034.285714   5.714286
1999     1999      2   4072.000000   4080.000000   8.000000

[2000 rows x 5 columns]
2500
14048.0
2500
      task_id  VM_ID    Start_time   Finish_time  Exec_time
0           0      3      0.000000      5.714286   5.714286
1           1      3      5.714286     11.428571   5.714286
2           2      3     11.428571     17.142857   5.714286
3           3      1      0.000000     16.000000  16.000000
4           4      3     17.142857     22.857143   5.714286
...       ...    ...           ...           ...        ...
2495     2495      2   5472.000000   5480.000000   8.000000
2496     2496      1  14000.000000  14016.000000  16.000000
2497     2497      1  14016.000000  14032.000000  16.000000
2498     2498      2   5480.000000   5488.000000   8.000000
2499     2499      1  14032.000000  14048.000000  16.000000

[2500 rows x 5 columns]
algo not found
100
188.57142857142858
100
    task_id  VM_ID  Start_time  Finish_time  Exec_time
0         0      1    0.000000    16.000000  16.000000
1         1      2    0.000000     8.000000   8.000000
2         2      1   16.000000    32.000000  16.000000
3         3      3    0.000000     5.714286   5.714286
4         4      1   32.000000    48.000000  16.000000
..      ...    ...         ...          ...        ...
95       95      2  168.000000   176.000000   8.000000
96       96      2  176.000000   184.000000   8.000000
97       97      4  182.857143   188.571429   5.714286
98       98      3  177.142857   182.857143   5.714286
99       99      3  182.857143   188.571429   5.714286

[100 rows x 5 columns]
500
1488.0
500
     task_id  VM_ID   Start_time  Finish_time  Exec_time
0          0      3     0.000000     5.714286   5.714286
1          1      3     5.714286    11.428571   5.714286
2          2      3    11.428571    17.142857   5.714286
3          3      3    17.142857    22.857143   5.714286
4          4      2     0.000000     8.000000   8.000000
..       ...    ...          ...          ...        ...
495      495      3   914.285714   920.000000   5.714286
496      496      2  1472.000000  1480.000000   8.000000
497      497      1  1472.000000  1488.000000  16.000000
498      498      2  1480.000000  1488.000000   8.000000
499      499      3   920.000000   925.714286   5.714286

[500 rows x 5 columns]
1000
3264.0
1000
     task_id  VM_ID   Start_time  Finish_time  Exec_time
0          0      1     0.000000    16.000000  16.000000
1          1      1    16.000000    32.000000  16.000000
2          2      1    32.000000    48.000000  16.000000
3          3      2     0.000000     8.000000   8.000000
4          4      1    48.000000    64.000000  16.000000
..       ...    ...          ...          ...        ...
995      995      1  3232.000000  3248.000000  16.000000
996      996      0  3232.000000  3248.000000  16.000000
997      997      4   365.714286   371.428571   5.714286
998      998      2  3248.000000  3256.000000   8.000000
999      999      2  3256.000000  3264.000000   8.000000

[1000 rows x 5 columns]
1500
5088.0
1500
      task_id  VM_ID   Start_time  Finish_time  Exec_time
0           0      2     0.000000     8.000000   8.000000
1           1      2     8.000000    16.000000   8.000000
2           2      3     0.000000     5.714286   5.714286
3           3      2    16.000000    24.000000   8.000000
4           4      1     0.000000    16.000000  16.000000
...       ...    ...          ...          ...        ...
1495     1495      3  2588.571429  2594.285714   5.714286
1496     1496      2  5064.000000  5072.000000   8.000000
1497     1497      1  5072.000000  5088.000000  16.000000
1498     1498      4   525.714286   531.428571   5.714286
1499     1499      2  5072.000000  5080.000000   8.000000

[1500 rows x 5 columns]
2000
6928.0
2000
      task_id  VM_ID   Start_time  Finish_time  Exec_time
0           0      3     0.000000     5.714286   5.714286
1           1      1     0.000000    16.000000  16.000000
2           2      2     0.000000     8.000000   8.000000
3           3      3     5.714286    11.428571   5.714286
4           4      3    11.428571    17.142857   5.714286
...       ...    ...          ...          ...        ...
1995     1995      3  3371.428571  3377.142857   5.714286
1996     1996      3  3377.142857  3382.857143   5.714286
1997     1997      3  3382.857143  3388.571429   5.714286
1998     1998      2  6912.000000  6920.000000   8.000000
1999     1999      2  6920.000000  6928.000000   8.000000

[2000 rows x 5 columns]
2500
8688.0
2500
      task_id  VM_ID   Start_time  Finish_time  Exec_time
0           0      2     0.000000     8.000000   8.000000
1           1      2     8.000000    16.000000   8.000000
2           2      2    16.000000    24.000000   8.000000
3           3      2    24.000000    32.000000   8.000000
4           4      2    32.000000    40.000000   8.000000
...       ...    ...          ...          ...        ...
2495     2495      2  8664.000000  8672.000000   8.000000
2496     2496      3  4474.285714  4480.000000   5.714286
2497     2497      2  8672.000000  8680.000000   8.000000
2498     2498      2  8680.000000  8688.000000   8.000000
2499     2499      3  4480.000000  4485.714286   5.714286

[2500 rows x 5 columns]
100

<ipython-input-8-e9652d172dbe>:97: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2_exe.insert(1, f,exe1)
<ipython-input-8-e9652d172dbe>:98: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2_start.insert(1, f,average_start)
<ipython-input-8-e9652d172dbe>:99: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2_finish.insert(1, f,average_finish)
<ipython-input-8-e9652d172dbe>:100: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2_aexe.insert(1, f,average_exe)
<ipython-input-8-e9652d172dbe>:101: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2_util.insert(1, f,utili1)
<ipython-input-8-e9652d172dbe>:102: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2_power.insert(1, f,power)

188.57142857142858
100
    task_id  VM_ID  Start_time  Finish_time  Exec_time
0         0      4    0.000000     5.714286   5.714286
1         1      3    0.000000     5.714286   5.714286
2         2      2    0.000000     8.000000   8.000000
3         3      4    5.714286    11.428571   5.714286
4         4      4   11.428571    17.142857   5.714286
..      ...    ...         ...          ...        ...
95       95      2  160.000000   168.000000   8.000000
96       96      2  168.000000   176.000000   8.000000
97       97      4  182.857143   188.571429   5.714286
98       98      3  182.857143   188.571429   5.714286
99       99      2  176.000000   184.000000   8.000000

[100 rows x 5 columns]
500
1119.999999999997
500
     task_id  VM_ID   Start_time  Finish_time  Exec_time
0          0      2     0.000000     8.000000   8.000000
1          1      3     0.000000     5.714286   5.714286
2          2      2     8.000000    16.000000   8.000000
3          3      4     0.000000     5.714286   5.714286
4          4      3     5.714286    11.428571   5.714286
..       ...    ...          ...          ...        ...
495      495      1  1072.000000  1088.000000  16.000000
496      496      3  1102.857143  1108.571429   5.714286
497      497      3  1108.571429  1114.285714   5.714286
498      498      2  1096.000000  1104.000000   8.000000
499      499      3  1114.285714  1120.000000   5.714286

[500 rows x 5 columns]
1000
2992.0
1000
     task_id  VM_ID   Start_time  Finish_time  Exec_time
0          0      3     0.000000     5.714286   5.714286
1          1      1     0.000000    16.000000  16.000000
2          2      2     0.000000     8.000000   8.000000
3          3      2     8.000000    16.000000   8.000000
4          4      2    16.000000    24.000000   8.000000
..       ...    ...          ...          ...        ...
995      995      2  2936.000000  2944.000000   8.000000
996      996      4   565.714286   571.428571   5.714286
997      997      2  2944.000000  2952.000000   8.000000
998      998      3  1960.000000  1965.714286   5.714286
999      999      0  1960.000000  1965.714286   5.714286

[1000 rows x 5 columns]
1500
4704.0
1500
      task_id  VM_ID   Start_time  Finish_time  Exec_time
0           0      3     0.000000     5.714286   5.714286
1           1      3     5.714286    11.428571   5.714286
2           2      4     0.000000     5.714286   5.714286
3           3      2     0.000000     8.000000   8.000000
4           4      2     8.000000    16.000000   8.000000
...       ...    ...          ...          ...        ...
1495     1495      1  4688.000000  4704.000000  16.000000
1496     1496      3  2948.571429  2954.285714   5.714286
1497     1497      2  4688.000000  4696.000000   8.000000
1498     1498      3  2954.285714  2960.000000   5.714286
1499     1499      2  4696.000000  4704.000000   8.000000

[1500 rows x 5 columns]
2000
6848.0
2000
      task_id  VM_ID   Start_time  Finish_time  Exec_time
0           0      4     0.000000     5.714286   5.714286
1           1      1     0.000000    16.000000  16.000000
2           2      1    16.000000    32.000000  16.000000
3           3      2     0.000000     8.000000   8.000000
4           4      1    32.000000    48.000000  16.000000
...       ...    ...          ...          ...        ...
1995     1995      2  6584.000000  6592.000000   8.000000
1996     1996      1  6816.000000  6832.000000  16.000000
1997     1997      2  6592.000000  6600.000000   8.000000
1998     1998      1  6832.000000  6848.000000  16.000000
1999     1999      3  3331.428571  3337.142857   5.714286

[2000 rows x 5 columns]
2500
8728.0
2500
      task_id  VM_ID   Start_time  Finish_time  Exec_time
0           0      2     0.000000     8.000000   8.000000
1           1      3     0.000000     5.714286   5.714286
2           2      2     8.000000    16.000000   8.000000
3           3      3     5.714286    11.428571   5.714286
4           4      3    11.428571    17.142857   5.714286
...       ...    ...          ...          ...        ...
2495     2495      2  8704.000000  8712.000000   8.000000
2496     2496      2  8712.000000  8720.000000   8.000000
2497     2497      1  8704.000000  8720.000000  16.000000
2498     2498      2  8720.000000  8728.000000   8.000000
2499     2499      3  4137.142857  4142.857143   5.714286

[2500 rows x 5 columns]
100

<ipython-input-8-e9652d172dbe>:97: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2_exe.insert(1, f,exe1)
<ipython-input-8-e9652d172dbe>:98: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2_start.insert(1, f,average_start)
<ipython-input-8-e9652d172dbe>:99: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2_finish.insert(1, f,average_finish)
<ipython-input-8-e9652d172dbe>:100: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2_aexe.insert(1, f,average_exe)
<ipython-input-8-e9652d172dbe>:101: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2_util.insert(1, f,utili1)
<ipython-input-8-e9652d172dbe>:102: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2_power.insert(1, f,power)

416.0
100
    task_id  VM_ID  Start_time  Finish_time  Exec_time
0         0      1    0.000000    16.000000  16.000000
1         1      0    0.000000    16.000000  16.000000
2         2      2    0.000000     8.000000   8.000000
3         3      3    0.000000     5.714286   5.714286
4         4      4    0.000000     5.714286   5.714286
..      ...    ...         ...          ...        ...
95       95      4  120.000000   125.714286   5.714286
96       96      2  224.000000   232.000000   8.000000
97       97      3  114.285714   120.000000   5.714286
98       98      2  232.000000   240.000000   8.000000
99       99      3  120.000000   125.714286   5.714286

[100 rows x 5 columns]
500
2576.0
500
     task_id  VM_ID   Start_time  Finish_time  Exec_time
0          0      4     0.000000     5.714286   5.714286
1          1      3     0.000000     5.714286   5.714286
2          2      0     0.000000     5.714286   5.714286
3          3      4     5.714286    11.428571   5.714286
4          4      0     5.714286    11.428571   5.714286
..       ...    ...          ...          ...        ...
495      495      3   622.857143   628.571429   5.714286
496      496      2  1112.000000  1120.000000   8.000000
497      497      2  1120.000000  1128.000000   8.000000
498      498      3   628.571429   634.285714   5.714286
499      499      4   491.428571   497.142857   5.714286

[500 rows x 5 columns]
1000
5392.0
1000
     task_id  VM_ID   Start_time  Finish_time  Exec_time
0          0      2     0.000000     8.000000   8.000000
1          1      1     0.000000    16.000000  16.000000
2          2      3     0.000000     5.714286   5.714286
3          3      3     5.714286    11.428571   5.714286
4          4      2     8.000000    16.000000   8.000000
..       ...    ...          ...          ...        ...
995      995      0   851.428571   857.142857   5.714286
996      996      3  1365.714286  1371.428571   5.714286
997      997      2  2160.000000  2168.000000   8.000000
998      998      2  2168.000000  2176.000000   8.000000
999      999      2  2176.000000  2184.000000   8.000000

[1000 rows x 5 columns]
1500
8112.0
1500
      task_id  VM_ID   Start_time  Finish_time  Exec_time
0           0      1     0.000000    16.000000  16.000000
1           1      3     0.000000     5.714286   5.714286
2           2      2     0.000000     8.000000   8.000000
3           3      4     0.000000     5.714286   5.714286
4           4      4     5.714286    11.428571   5.714286
...       ...    ...          ...          ...        ...
1495     1495      2  3256.000000  3264.000000   8.000000
1496     1496      2  3264.000000  3272.000000   8.000000
1497     1497      2  3272.000000  3280.000000   8.000000
1498     1498      1  8096.000000  8112.000000  16.000000
1499     1499      3  2131.428571  2137.142857   5.714286

[1500 rows x 5 columns]
2000
11088.0
2000
      task_id  VM_ID    Start_time   Finish_time  Exec_time
0           0      3      0.000000      5.714286   5.714286
1           1      3      5.714286     11.428571   5.714286
2           2      4      0.000000      5.714286   5.714286
3           3      3     11.428571     17.142857   5.714286
4           4      2      0.000000      8.000000   8.000000
...       ...    ...           ...           ...        ...
1995     1995      3   2880.000000   2885.714286   5.714286
1996     1996      1  11056.000000  11072.000000  16.000000
1997     1997      3   2885.714286   2891.428571   5.714286
1998     1998      1  11072.000000  11088.000000  16.000000
1999     1999      2   4320.000000   4328.000000   8.000000

[2000 rows x 5 columns]
2500
14176.0
2500
      task_id  VM_ID    Start_time   Finish_time  Exec_time
0           0      2      0.000000      8.000000   8.000000
1           1      3      0.000000      5.714286   5.714286
2           2      4      0.000000      5.714286   5.714286
3           3      0      0.000000      5.714286   5.714286
4           4      2      8.000000     16.000000   8.000000
...       ...    ...           ...           ...        ...
2495     2495      3   3605.714286   3611.428571   5.714286
2496     2496      2   5552.000000   5560.000000   8.000000
2497     2497      1  14144.000000  14160.000000  16.000000
2498     2498      3   3611.428571   3617.142857   5.714286
2499     2499      0   3611.428571   3617.142857   5.714286

[2500 rows x 5 columns]

<ipython-input-8-e9652d172dbe>:97: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2_exe.insert(1, f,exe1)
<ipython-input-8-e9652d172dbe>:98: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2_start.insert(1, f,average_start)
<ipython-input-8-e9652d172dbe>:99: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2_finish.insert(1, f,average_finish)
<ipython-input-8-e9652d172dbe>:100: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2_aexe.insert(1, f,average_exe)
<ipython-input-8-e9652d172dbe>:101: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2_util.insert(1, f,utili1)
<ipython-input-8-e9652d172dbe>:102: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2_power.insert(1, f,power)

100
217.1428571428572
100
    task_id  VM_ID  Start_time  Finish_time  Exec_time
0         0      4    0.000000     5.714286   5.714286
1         1      4    5.714286    11.428571   5.714286
2         2      4   11.428571    17.142857   5.714286
3         3      2    0.000000     8.000000   8.000000
4         4      2    8.000000    16.000000   8.000000
..      ...    ...         ...          ...        ...
95       95      3  114.285714   120.000000   5.714286
96       96      3  120.000000   125.714286   5.714286
97       97      2  200.000000   208.000000   8.000000
98       98      2  208.000000   216.000000   8.000000
99       99      4  211.428571   217.142857   5.714286

[100 rows x 5 columns]
500
1177.1428571428548
500
     task_id  VM_ID   Start_time  Finish_time  Exec_time
0          0      4     0.000000     5.714286   5.714286
1          1      4     5.714286    11.428571   5.714286
2          2      2     0.000000     8.000000   8.000000
3          3      1     0.000000    16.000000  16.000000
4          4      3     0.000000     5.714286   5.714286
..       ...    ...          ...          ...        ...
495      495      0   428.571429   434.285714   5.714286
496      496      2  1136.000000  1144.000000   8.000000
497      497      2  1144.000000  1152.000000   8.000000
498      498      3   434.285714   440.000000   5.714286
499      499      4  1171.428571  1177.142857   5.714286

[500 rows x 5 columns]
1000
2768.0
1000
     task_id  VM_ID   Start_time  Finish_time  Exec_time
0          0      4     0.000000     5.714286   5.714286
1          1      0     0.000000     5.714286   5.714286
2          2      4     5.714286    11.428571   5.714286
3          3      2     0.000000     8.000000   8.000000
4          4      3     0.000000     5.714286   5.714286
..       ...    ...          ...          ...        ...
995      995      4  2068.571429  2074.285714   5.714286
996      996      4  2074.285714  2080.000000   5.714286
997      997      2  2744.000000  2752.000000   8.000000
998      998      2  2752.000000  2760.000000   8.000000
999      999      2  2760.000000  2768.000000   8.000000

[1000 rows x 5 columns]
1500
4464.0
1500
      task_id  VM_ID   Start_time  Finish_time  Exec_time
0           0      4     0.000000     5.714286   5.714286
1           1      2     0.000000     8.000000   8.000000
2           2      2     8.000000    16.000000   8.000000
3           3      1     0.000000    16.000000  16.000000
4           4      3     0.000000     5.714286   5.714286
...       ...    ...          ...          ...        ...
1495     1495      2  4432.000000  4440.000000   8.000000
1496     1496      4  2897.142857  2902.857143   5.714286
1497     1497      2  4440.000000  4448.000000   8.000000
1498     1498      4  2902.857143  2908.571429   5.714286
1499     1499      2  4448.000000  4456.000000   8.000000

[1500 rows x 5 columns]
2000
6184.0
2000
      task_id  VM_ID   Start_time  Finish_time  Exec_time
0           0      4     0.000000     5.714286   5.714286
1           1      4     5.714286    11.428571   5.714286
2           2      2     0.000000     8.000000   8.000000
3           3      3     0.000000     5.714286   5.714286
4           4      3     5.714286    11.428571   5.714286
...       ...    ...          ...          ...        ...
1995     1995      0  3640.000000  3645.714286   5.714286
1996     1996      4  3645.714286  3651.428571   5.714286
1997     1997      4  3651.428571  3657.142857   5.714286
1998     1998      2  6176.000000  6184.000000   8.000000
1999     1999      4  3657.142857  3662.857143   5.714286

[2000 rows x 5 columns]
2500
8024.0
2500
      task_id  VM_ID   Start_time  Finish_time  Exec_time
0           0      2     0.000000     8.000000   8.000000
1           1      4     0.000000     5.714286   5.714286
2           2      4     5.714286    11.428571   5.714286
3           3      4    11.428571    17.142857   5.714286
4           4      3     0.000000     5.714286   5.714286
...       ...    ...          ...          ...        ...
2495     2495      4  4331.428571  4337.142857   5.714286
2496     2496      2  8000.000000  8008.000000   8.000000
2497     2497      0  8000.000000  8008.000000   8.000000
2498     2498      2  8008.000000  8016.000000   8.000000
2499     2499      2  8016.000000  8024.000000   8.000000

[2500 rows x 5 columns]

<ipython-input-8-e9652d172dbe>:97: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2_exe.insert(1, f,exe1)
<ipython-input-8-e9652d172dbe>:98: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2_start.insert(1, f,average_start)
<ipython-input-8-e9652d172dbe>:99: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2_finish.insert(1, f,average_finish)
<ipython-input-8-e9652d172dbe>:100: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2_aexe.insert(1, f,average_exe)
<ipython-input-8-e9652d172dbe>:101: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2_util.insert(1, f,utili1)
<ipython-input-8-e9652d172dbe>:102: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2_power.insert(1, f,power)

100
200.00000000000003
100
    task_id  VM_ID  Start_time  Finish_time  Exec_time
0         0      1    0.000000    16.000000  16.000000
1         1      2    0.000000     8.000000   8.000000
2         2      1   16.000000    32.000000  16.000000
3         3      4    0.000000     5.714286   5.714286
4         4      3    0.000000     5.714286   5.714286
..      ...    ...         ...          ...        ...
95       95      4  188.571429   194.285714   5.714286
96       96      4  194.285714   200.000000   5.714286
97       97      2  160.000000   168.000000   8.000000
98       98      2  168.000000   176.000000   8.000000
99       99      3  188.571429   194.285714   5.714286

[100 rows x 5 columns]
500
1028.5714285714246
500
     task_id  VM_ID   Start_time  Finish_time  Exec_time
0          0      2     0.000000     8.000000   8.000000
1          1      2     8.000000    16.000000   8.000000
2          2      2    16.000000    24.000000   8.000000
3          3      4     0.000000     5.714286   5.714286
4          4      4     5.714286    11.428571   5.714286
..       ...    ...          ...          ...        ...
495      495      4  1000.000000  1005.714286   5.714286
496      496      4  1005.714286  1011.428571   5.714286
497      497      4  1011.428571  1017.142857   5.714286
498      498      4  1017.142857  1022.857143   5.714286
499      499      4  1022.857143  1028.571429   5.714286

[500 rows x 5 columns]
1000
2028.571428571436
1000
     task_id  VM_ID   Start_time  Finish_time  Exec_time
0          0      4     0.000000     5.714286   5.714286
1          1      3     0.000000     5.714286   5.714286
2          2      3     5.714286    11.428571   5.714286
3          3      3    11.428571    17.142857   5.714286
4          4      4     5.714286    11.428571   5.714286
..       ...    ...          ...          ...        ...
995      995      3  1737.142857  1742.857143   5.714286
996      996      4  2011.428571  2017.142857   5.714286
997      997      3  1742.857143  1748.571429   5.714286
998      998      4  2017.142857  2022.857143   5.714286
999      999      4  2022.857143  2028.571429   5.714286

[1000 rows x 5 columns]
1500
3000.000000000018
1500
      task_id  VM_ID   Start_time  Finish_time  Exec_time
0           0      3     0.000000     5.714286   5.714286
1           1      4     0.000000     5.714286   5.714286
2           2      2     0.000000     8.000000   8.000000
3           3      2     8.000000    16.000000   8.000000
4           4      3     5.714286    11.428571   5.714286
...       ...    ...          ...          ...        ...
1495     1495      4  2908.571429  2914.285714   5.714286
1496     1496      4  2914.285714  2920.000000   5.714286
1497     1497      4  2920.000000  2925.714286   5.714286
1498     1498      2  2824.000000  2832.000000   8.000000
1499     1499      1  1728.000000  1744.000000  16.000000

[1500 rows x 5 columns]
2000
4120.000000000029
2000
      task_id  VM_ID   Start_time  Finish_time  Exec_time
0           0      1     0.000000    16.000000  16.000000
1           1      4     0.000000     5.714286   5.714286
2           2      2     0.000000     8.000000   8.000000
3           3      4     5.714286    11.428571   5.714286
4           4      3     0.000000     5.714286   5.714286
...       ...    ...          ...          ...        ...
1995     1995      4  4102.857143  4108.571429   5.714286
1996     1996      4  4108.571429  4114.285714   5.714286
1997     1997      4  4114.285714  4120.000000   5.714286
1998     1998      3  3622.857143  3628.571429   5.714286
1999     1999      3  3628.571429  3634.285714   5.714286

[2000 rows x 5 columns]
2500
4994.285714285684
2500
      task_id  VM_ID   Start_time  Finish_time  Exec_time
0           0      4     0.000000     5.714286   5.714286
1           1      4     5.714286    11.428571   5.714286
2           2      3     0.000000     5.714286   5.714286
3           3      3     5.714286    11.428571   5.714286
4           4      3    11.428571    17.142857   5.714286
...       ...    ...          ...          ...        ...
2495     2495      4  4971.428571  4977.142857   5.714286
2496     2496      4  4977.142857  4982.857143   5.714286
2497     2497      4  4982.857143  4988.571429   5.714286
2498     2498      2  4984.000000  4992.000000   8.000000
2499     2499      4  4988.571429  4994.285714   5.714286

[2500 rows x 5 columns]

<ipython-input-8-e9652d172dbe>:97: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2_exe.insert(1, f,exe1)
<ipython-input-8-e9652d172dbe>:98: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2_start.insert(1, f,average_start)
<ipython-input-8-e9652d172dbe>:99: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2_finish.insert(1, f,average_finish)
<ipython-input-8-e9652d172dbe>:100: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2_aexe.insert(1, f,average_exe)
<ipython-input-8-e9652d172dbe>:101: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2_util.insert(1, f,utili1)
<ipython-input-8-e9652d172dbe>:102: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2_power.insert(1, f,power)

100
An exception occurred local variable 'start' referenced before assignment
500
2688.0
500
     task_id  VM_ID   Start_time  Finish_time  Exec_time
0          0      2     0.000000     8.000000   8.000000
1          1      2     8.000000    16.000000   8.000000
2          2      3     0.000000     5.714286   5.714286
3          3      3     5.714286    11.428571   5.714286
4          4      2    16.000000    24.000000   8.000000
..       ...    ...          ...          ...        ...
495      495      4   308.571429   314.285714   5.714286
496      496      2  1096.000000  1104.000000   8.000000
497      497      2  1104.000000  1112.000000   8.000000
498      498      1  2672.000000  2688.000000  16.000000
499      499      4   314.285714   320.000000   5.714286

[500 rows x 5 columns]
1000
5536.0
1000
     task_id  VM_ID   Start_time  Finish_time  Exec_time
0          0      3     0.000000     5.714286   5.714286
1          1      0     0.000000     5.714286   5.714286
2          2      1    16.000000    32.000000  16.000000
3          3      2     0.000000     8.000000   8.000000
4          4      2     8.000000    16.000000   8.000000
..       ...    ...          ...          ...        ...
995      995      1  5520.000000  5536.000000  16.000000
996      996      3  1554.285714  1560.000000   5.714286
997      997      4   605.714286   611.428571   5.714286
998      998      3  1560.000000  1565.714286   5.714286
999      999      3  1565.714286  1571.428571   5.714286

[1000 rows x 5 columns]
1500
8464.0
1500
      task_id  VM_ID   Start_time  Finish_time  Exec_time
0           0      3     0.000000     5.714286   5.714286
1           1      1     0.000000    16.000000  16.000000
2           2      1    16.000000    32.000000  16.000000
3           3      3     5.714286    11.428571   5.714286
4           4      2     0.000000     8.000000   8.000000
...       ...    ...          ...          ...        ...
1495     1495      1  8432.000000  8448.000000  16.000000
1496     1496      3  2120.000000  2125.714286   5.714286
1497     1497      0  2120.000000  2125.714286   5.714286
1498     1498      3  2125.714286  2131.428571   5.714286
1499     1499      2  3424.000000  3432.000000   8.000000

[1500 rows x 5 columns]
2000
11408.0
2000
      task_id  VM_ID   Start_time  Finish_time  Exec_time
0           0      3     0.000000     5.714286   5.714286
1           1      3     5.714286    11.428571   5.714286
2           2      3    11.428571    17.142857   5.714286
3           3      1     0.000000    16.000000  16.000000
4           4      1    16.000000    32.000000  16.000000
...       ...    ...          ...          ...        ...
1995     1995      4  1565.714286  1571.428571   5.714286
1996     1996      2  4136.000000  4144.000000   8.000000
1997     1997      2  4144.000000  4152.000000   8.000000
1998     1998      4  1571.428571  1577.142857   5.714286
1999     1999      2  4152.000000  4160.000000   8.000000

[2000 rows x 5 columns]
2500
An exception occurred local variable 'start' referenced before assignment
algo not found
100
240.0
100
    task_id  VM_ID  Start_time  Finish_time  Exec_time
0         0      3    0.000000     5.714286   5.714286
1         1      4    0.000000     5.714286   5.714286
2         2      0    0.000000     5.714286   5.714286
3         3      3    5.714286    11.428571   5.714286
4         4      3   11.428571    17.142857   5.714286
..      ...    ...         ...          ...        ...
95       95      3  217.142857   222.857143   5.714286
96       96      2  192.000000   200.000000   8.000000
97       97      2  200.000000   208.000000   8.000000
98       98      3  222.857143   228.571429   5.714286
99       99      3  228.571429   234.285714   5.714286

[100 rows x 5 columns]
500
1308.5714285714278
500
     task_id  VM_ID   Start_time  Finish_time  Exec_time
0          0      3     0.000000     5.714286   5.714286
1          1      2     0.000000     8.000000   8.000000
2          2      1     0.000000    16.000000  16.000000
3          3      2     8.000000    16.000000   8.000000
4          4      3     5.714286    11.428571   5.714286
..       ...    ...          ...          ...        ...
495      495      2  1288.000000  1296.000000   8.000000
496      496      3  1297.142857  1302.857143   5.714286
497      497      1  1280.000000  1296.000000  16.000000
498      498      4   154.285714   160.000000   5.714286
499      499      3  1302.857143  1308.571429   5.714286

[500 rows x 5 columns]
1000
2462.857142857155
1000
     task_id  VM_ID   Start_time  Finish_time  Exec_time
0          0      1     0.000000    16.000000  16.000000
1          1      1    16.000000    32.000000  16.000000
2          2      4     0.000000     5.714286   5.714286
3          3      4     5.714286    11.428571   5.714286
4          4      4    11.428571    17.142857   5.714286
..       ...    ...          ...          ...        ...
995      995      2  2328.000000  2336.000000   8.000000
996      996      2  2336.000000  2344.000000   8.000000
997      997      2  2344.000000  2352.000000   8.000000
998      998      2  2352.000000  2360.000000   8.000000
999      999      3  2457.142857  2462.857143   5.714286

[1000 rows x 5 columns]
1500
3576.0
1500
      task_id  VM_ID   Start_time  Finish_time  Exec_time
0           0      2     0.000000     8.000000   8.000000
1           1      0     0.000000     8.000000   8.000000
2           2      4     0.000000     5.714286   5.714286
3           3      2     8.000000    16.000000   8.000000
4           4      2    16.000000    24.000000   8.000000
...       ...    ...          ...          ...        ...
1495     1495      1  3536.000000  3552.000000  16.000000
1496     1496      2  3568.000000  3576.000000   8.000000
1497     1497      3  3102.857143  3108.571429   5.714286
1498     1498      3  3108.571429  3114.285714   5.714286
1499     1499      3  3114.285714  3120.000000   5.714286

[1500 rows x 5 columns]
2000
5072.0
2000
      task_id  VM_ID   Start_time  Finish_time  Exec_time
0           0      2     0.000000     8.000000   8.000000
1           1      1     0.000000    16.000000  16.000000
2           2      1    16.000000    32.000000  16.000000
3           3      4     0.000000     5.714286   5.714286
4           4      0     0.000000     5.714286   5.714286
...       ...    ...          ...          ...        ...
1995     1995      3  3045.714286  3051.428571   5.714286
1996     1996      4  2960.000000  2965.714286   5.714286
1997     1997      4  2965.714286  2971.428571   5.714286
1998     1998      2  5016.000000  5024.000000   8.000000
1999     1999      2  5024.000000  5032.000000   8.000000

[2000 rows x 5 columns]
2500
6479.999999999868
2500
      task_id  VM_ID   Start_time  Finish_time  Exec_time
0           0      3     0.000000     5.714286   5.714286
1           1      1     0.000000    16.000000  16.000000
2           2      1    16.000000    32.000000  16.000000
3           3      2     0.000000     8.000000   8.000000
4           4      4     0.000000     5.714286   5.714286
...       ...    ...          ...          ...        ...
2495     2495      4  1148.571429  1154.285714   5.714286
2496     2496      4  1154.285714  1160.000000   5.714286
2497     2497      3  6474.285714  6480.000000   5.714286
2498     2498      2  6112.000000  6120.000000   8.000000
2499     2499      4  1160.000000  1165.714286   5.714286

[2500 rows x 5 columns]

<ipython-input-8-e9652d172dbe>:97: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2_exe.insert(1, f,exe1)
<ipython-input-8-e9652d172dbe>:98: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2_start.insert(1, f,average_start)
<ipython-input-8-e9652d172dbe>:99: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2_finish.insert(1, f,average_finish)
<ipython-input-8-e9652d172dbe>:100: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2_aexe.insert(1, f,average_exe)
<ipython-input-8-e9652d172dbe>:101: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2_util.insert(1, f,utili1)
<ipython-input-8-e9652d172dbe>:102: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2_power.insert(1, f,power)

100
304.0
100
    task_id  VM_ID  Start_time  Finish_time  Exec_time
0         0      2    0.000000     8.000000   8.000000
1         1      2    8.000000    16.000000   8.000000
2         2      1    0.000000    16.000000  16.000000
3         3      3    0.000000     5.714286   5.714286
4         4      2   16.000000    24.000000   8.000000
..      ...    ...         ...          ...        ...
95       95      2  248.000000   256.000000   8.000000
96       96      2  256.000000   264.000000   8.000000
97       97      3  211.428571   217.142857   5.714286
98       98      2  264.000000   272.000000   8.000000
99       99      3  217.142857   222.857143   5.714286

[100 rows x 5 columns]
500
1824.0
500
     task_id  VM_ID   Start_time  Finish_time  Exec_time
0          0      1     0.000000    16.000000  16.000000
1          1      2     0.000000     8.000000   8.000000
2          2      2     8.000000    16.000000   8.000000
3          3      2    16.000000    24.000000   8.000000
4          4      1    16.000000    32.000000  16.000000
..       ...    ...          ...          ...        ...
495      495      0  1784.000000  1792.000000   8.000000
496      496      3   702.857143   708.571429   5.714286
497      497      2  1792.000000  1800.000000   8.000000
498      498      3   708.571429   714.285714   5.714286
499      499      3   714.285714   720.000000   5.714286

[500 rows x 5 columns]
1000
3920.0
1000
     task_id  VM_ID   Start_time  Finish_time  Exec_time
0          0      1     0.000000    16.000000  16.000000
1          1      3     0.000000     5.714286   5.714286
2          2      2     0.000000     8.000000   8.000000
3          3      2     8.000000    16.000000   8.000000
4          4      3     5.714286    11.428571   5.714286
..       ...    ...          ...          ...        ...
995      995      2  3888.000000  3896.000000   8.000000
996      996      2  3896.000000  3904.000000   8.000000
997      997      2  3904.000000  3912.000000   8.000000
998      998      3  1308.571429  1314.285714   5.714286
999      999      3  1314.285714  1320.000000   5.714286

[1000 rows x 5 columns]
1500
6560.0
1500
      task_id  VM_ID  Start_time  Finish_time  Exec_time
0           0      2    0.000000     8.000000   8.000000
1           1      2    8.000000    16.000000   8.000000
2           2      2   16.000000    24.000000   8.000000
3           3      3    0.000000     5.714286   5.714286
4           4      2   24.000000    32.000000   8.000000
...       ...    ...         ...          ...        ...
1495     1495      3  548.571429   554.285714   5.714286
1496     1496      0  548.571429   554.285714   5.714286
1497     1497      0  548.571429   554.285714   5.714286
1498     1498      0  548.571429   554.285714   5.714286
1499     1499      0  548.571429   554.285714   5.714286

[1500 rows x 5 columns]
2000
8112.0
2000
      task_id  VM_ID   Start_time  Finish_time  Exec_time
0           0      4     0.000000     5.714286   5.714286
1           1      0     0.000000     5.714286   5.714286
2           2      2     0.000000     8.000000   8.000000
3           3      2     8.000000    16.000000   8.000000
4           4      0     8.000000    16.000000   8.000000
...       ...    ...          ...          ...        ...
1995     1995      1  8080.000000  8096.000000  16.000000
1996     1996      4  2514.285714  2520.000000   5.714286
1997     1997      2  8032.000000  8040.000000   8.000000
1998     1998      4  2520.000000  2525.714286   5.714286
1999     1999      0  2520.000000  2525.714286   5.714286

[2000 rows x 5 columns]
2500
10016.0
2500
      task_id  VM_ID    Start_time   Finish_time  Exec_time
0           0      2      0.000000      8.000000   8.000000
1           1      2      8.000000     16.000000   8.000000
2           2      0      8.000000     16.000000   8.000000
3           3      1     16.000000     32.000000  16.000000
4           4      1     32.000000     48.000000  16.000000
...       ...    ...           ...           ...        ...
2495     2495      1   9984.000000  10000.000000  16.000000
2496     2496      1  10000.000000  10016.000000  16.000000
2497     2497      2   9616.000000   9624.000000   8.000000
2498     2498      3   3080.000000   3085.714286   5.714286
2499     2499      3   3085.714286   3091.428571   5.714286

[2500 rows x 5 columns]

<ipython-input-8-e9652d172dbe>:97: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2_exe.insert(1, f,exe1)
<ipython-input-8-e9652d172dbe>:98: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2_start.insert(1, f,average_start)
<ipython-input-8-e9652d172dbe>:99: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2_finish.insert(1, f,average_finish)
<ipython-input-8-e9652d172dbe>:100: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2_aexe.insert(1, f,average_exe)
<ipython-input-8-e9652d172dbe>:101: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2_util.insert(1, f,utili1)
<ipython-input-8-e9652d172dbe>:102: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2_power.insert(1, f,power)

100
205.71428571428575
100
    task_id  VM_ID  Start_time  Finish_time  Exec_time
0         0      1    0.000000    16.000000  16.000000
1         1      4    0.000000     5.714286   5.714286
2         2      2    0.000000     8.000000   8.000000
3         3      4    5.714286    11.428571   5.714286
4         4      3    0.000000     5.714286   5.714286
..      ...    ...         ...          ...        ...
95       95      4  188.571429   194.285714   5.714286
96       96      2  144.000000   152.000000   8.000000
97       97      4  194.285714   200.000000   5.714286
98       98      3  200.000000   205.714286   5.714286
99       99      1  144.000000   160.000000  16.000000

[100 rows x 5 columns]
500
1040.0
500
     task_id  VM_ID  Start_time  Finish_time  Exec_time
0          0      4    0.000000     5.714286   5.714286
1          1      4    5.714286    11.428571   5.714286
2          2      1    0.000000    16.000000  16.000000
3          3      3    0.000000     5.714286   5.714286
4          4      4   11.428571    17.142857   5.714286
..       ...    ...         ...          ...        ...
495      495      4  948.571429   954.285714   5.714286
496      496      3  960.000000   965.714286   5.714286
497      497      4  954.285714   960.000000   5.714286
498      498      4  960.000000   965.714286   5.714286
499      499      4  965.714286   971.428571   5.714286

[500 rows x 5 columns]
1000
1984.0
1000
     task_id  VM_ID   Start_time  Finish_time  Exec_time
0          0      3     0.000000     5.714286   5.714286
1          1      3     5.714286    11.428571   5.714286
2          2      4     0.000000     5.714286   5.714286
3          3      2     0.000000     8.000000   8.000000
4          4      4     5.714286    11.428571   5.714286
..       ...    ...          ...          ...        ...
995      995      1  1904.000000  1920.000000  16.000000
996      996      3  1828.571429  1834.285714   5.714286
997      997      4  1760.000000  1765.714286   5.714286
998      998      4  1765.714286  1771.428571   5.714286
999      999      4  1771.428571  1777.142857   5.714286

[1000 rows x 5 columns]
1500
3005.714285714304
1500
      task_id  VM_ID   Start_time  Finish_time  Exec_time
0           0      4     0.000000     5.714286   5.714286
1           1      3     0.000000     5.714286   5.714286
2           2      4     5.714286    11.428571   5.714286
3           3      3     5.714286    11.428571   5.714286
4           4      4    11.428571    17.142857   5.714286
...       ...    ...          ...          ...        ...
1495     1495      4  2988.571429  2994.285714   5.714286
1496     1496      3  2525.714286  2531.428571   5.714286
1497     1497      4  2994.285714  3000.000000   5.714286
1498     1498      3  2531.428571  2537.142857   5.714286
1499     1499      4  3000.000000  3005.714286   5.714286

[1500 rows x 5 columns]
2000
4085.7142857143162
2000
      task_id  VM_ID   Start_time  Finish_time  Exec_time
0           0      4     0.000000     5.714286   5.714286
1           1      2     0.000000     8.000000   8.000000
2           2      3     0.000000     5.714286   5.714286
3           3      3     5.714286    11.428571   5.714286
4           4      4     5.714286    11.428571   5.714286
...       ...    ...          ...          ...        ...
1995     1995      4  3868.571429  3874.285714   5.714286
1996     1996      4  3874.285714  3880.000000   5.714286
1997     1997      4  3880.000000  3885.714286   5.714286
1998     1998      4  3885.714286  3891.428571   5.714286
1999     1999      4  3891.428571  3897.142857   5.714286

[2000 rows x 5 columns]
2500
5128.0
2500
      task_id  VM_ID   Start_time  Finish_time  Exec_time
0           0      3     0.000000     5.714286   5.714286
1           1      2     0.000000     8.000000   8.000000
2           2      3     5.714286    11.428571   5.714286
3           3      4     0.000000     5.714286   5.714286
4           4      3    11.428571    17.142857   5.714286
...       ...    ...          ...          ...        ...
2495     2495      2  5120.000000  5128.000000   8.000000
2496     2496      4  4520.000000  4525.714286   5.714286
2497     2497      3  4382.857143  4388.571429   5.714286
2498     2498      4  4525.714286  4531.428571   5.714286
2499     2499      3  4388.571429  4394.285714   5.714286

[2500 rows x 5 columns]
      algo tasks  Average_Start_time  Average_Finish_time  average_Exec_time  \
0  CoatiOA   100           90.560000            97.325714           6.765714
1  CoatiOA   500          478.582857           485.435429           6.852571
2  CoatiOA  1000          928.206857           935.722286           7.515429
3  CoatiOA  1500         1398.448762          1405.946667           7.497905
4  CoatiOA  2000         1942.298857          1949.055429           6.756571
5  CoatiOA  2500         2330.442971          2337.965257           7.522286

   average_utlization    Execution       Power
0           69.777778   205.714286    4.306286
1           66.791209  1040.000000   20.838857
2           75.760369  1984.000000   45.092571
3           74.836502  3005.714286   67.481143
4           66.606993  4085.714286   81.641143
5           73.345220  5128.000000  112.834286
cp: cannot create directory '/content/drive/MyDrive/Cloudsim/exe': No such file or directory

<ipython-input-8-e9652d172dbe>:97: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2_exe.insert(1, f,exe1)
<ipython-input-8-e9652d172dbe>:98: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2_start.insert(1, f,average_start)
<ipython-input-8-e9652d172dbe>:99: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2_finish.insert(1, f,average_finish)
<ipython-input-8-e9652d172dbe>:100: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2_aexe.insert(1, f,average_exe)
<ipython-input-8-e9652d172dbe>:101: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2_util.insert(1, f,utili1)
<ipython-input-8-e9652d172dbe>:102: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2_power.insert(1, f,power)

In [ ]:
  %cp -r "/content/analysis_5.csv" "/content/drive/MyDrive/colab/Cloudsim/exe"
  %cp -r "/content/exe_5.csv" "/content/drive/MyDrive/colab/Cloudsim/exe"
  %cp -r "/content/start_5.csv" "/content/drive/MyDrive/colab/Cloudsim/exe"
  %cp -r "/content/finish_5.csv" "/content/drive/MyDrive/colab/Cloudsim/exe"
  %cp -r "/content/aexe_5.csv" "/content/drive/MyDrive/colab/Cloudsim/exe"
  %cp -r "/content/util_5.csv" "/content/drive/MyDrive/colab/Cloudsim/exe"
  %cp -r "/content/power_5.csv" "/content/drive/MyDrive/colab/Cloudsim/exe"